[package]
name = "longhorn-native-content-child-view-proof"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[build-dependencies]
tauri-build.workspace = true

[dependencies]
longhorn-core.workspace = true
longhorn-native-content.workspace = true
longhorn-tauri-native-content-child-view.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { workspace = true, features = ["wry"] }

[lints]
workspace = true
