// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A release line.
 *
 * All channels ship under one bundle identity, so an install moves between
 * them without reinstalling and without a second copy of its data.
 */
export type Channel = "production" | "beta" | "nightly";
