// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an update check ran.
 */
export type CheckKind = "automatic" | "user-initiated";
