// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallManager } from "./InstallManager";

/**
 * Why an install did not proceed.
 *
 * Deferral is a decision with a cause, never a silent skip: an update that
 * quietly does not happen is indistinguishable from one that is broken.
 */
export type DeferralCause = { "cause": "userPostponed" } | { "cause": "workInFlight", 
/**
 * What was in flight, for display.
 */
detail: string, } | { "cause": "installationNotWritable", 
/**
 * What could not be written, for display.
 */
detail: string, } | { "cause": "externallyManaged", 
/**
 * Who owns it, for display.
 */
manager: InstallManager, 
/**
 * What the user should run, when the answer is a command.
 */
command: string | null, } | { "cause": "installFailed", 
/**
 * What went wrong, for display.
 */
detail: string, };
