// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallManager } from "./InstallManager";

/**
 * Who owns the installed application.
 *
 * An application a package manager installed must not replace itself. Doing
 * so leaves the manager's database describing a version that is no longer on
 * disk: `brew list --versions` reports the old one, and the next
 * `brew upgrade --cask` either reverts the update or fails on a checksum it
 * did not expect.
 *
 * This is checked **before an update is offered**, not when the install is
 * attempted. Writability is the wrong signal: a Homebrew cask lands in
 * `/Applications`, which is group-writable by admin users on an ordinary
 * Mac, so a permission check passes and the desync happens quietly.
 */
export type InstallProvenance = { "kind": "selfManaged" } | { "kind": "externallyManaged", 
/**
 * Which one.
 */
manager: InstallManager, } | { "kind": "undetermined" };
