// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an update is being offered.
 *
 * kebab-case, alone in this domain -- every other string union here is
 * camelCase. Worth changing, and it cannot be changed here alone: Poodle
 * mirrors this union structurally, so the two spellings must move together
 * or `check:svelte` fails on the mismatch. Raised with Poodle 2026-08-13.
 */
export type OfferReason = "staged" | "below-minimum-version" | "user-initiated";
