// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an update is being offered.
 *
 * camelCase, as every other string union in this domain is. It was
 * kebab-case and alone in that, which read as a typo to anyone mirroring the
 * type. Poodle mirrors this union structurally, so the two spellings had to
 * move together -- they landed either side of 2026-08-13 and the window
 * between them was red on `check:svelte`, which is the drift check working.
 */
export type OfferReason = "staged" | "belowMinimumVersion" | "userInitiated";
