// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One kind of Longhorn-owned work that must settle before a restart.
 *
 * An update that relaunches mid-commit is data loss, and only Longhorn knows
 * what is outstanding — this is the part of the update path a consuming
 * application could not write for itself.
 */
export type QuiescenceKind = "pending-flush" | "open-transfer-session" | "running-operation";
