[package]
name = "longhorn-jetstream-command-artifact-proof"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
longhorn-command.workspace = true
longhorn-core.workspace = true
serde_json.workspace = true

[lints]
workspace = true
