// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which persistent store refused a load.
 */
export type CompatibilityStore = "Configuration" | "History" | "HistoryTree" | "BackupArchive";
