// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bound on an entitlement, where one applies.
 */
export type Limit = null | bigint;
