// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point in time, as seconds since the Unix epoch.
 *
 * Deliberately a plain integer rather than a date type: this crate is pure
 * policy and never reads a clock. Every function that needs "now" is handed
 * one, which is also what makes expiry testable without waiting.
 */
export type Timestamp = number;
