// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * Whether the software may be used, and on what footing.
 */
export type Usability = { "state": "active" } | { "state": "inGrace", 
/**
 * When grace runs out.
 */
until: Timestamp, } | { "state": "useWindowExpired", 
/**
 * When it passed.
 */
at: Timestamp, } | { "state": "leaseLapsed", 
/**
 * When grace ran out.
 */
at: Timestamp, } | { "state": "clockRefused" };
