[package]
name = "longhorn-native-content-jetstream-artifact-proof"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
longhorn-native-content-artifact-proof-common.workspace = true
longhorn-native-content-backing-surface.workspace = true
