[package]
name = "longhorn-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
bindings = ["dep:ts-rs", "longhorn-core/bindings"]

[dependencies]
cap-std.workspace = true
fs4.workspace = true
longhorn-core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ts-rs = { workspace = true, optional = true }
zip.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tempfile.workspace = true

[lints]
workspace = true
