use std::{
    collections::BTreeSet,
    env,
    error::Error,
    fs, io,
    path::{Path, PathBuf},
    sync::LazyLock,
};

/// The one `ts-rs` configuration every declaration in every domain shares.
///
/// `ts-rs` 12 moved binding options off the environment and onto `Config`,
/// which `decl` now takes by reference. The default maps `u64`/`i64` to
/// `bigint` — the same default 11 had — and the wire contract already pins
/// every large-int field to `number` with `#[ts(type = "number")]`, because
/// `JSON.parse` never produces a `bigint`. An explicit, shared config keeps
/// the generated bytes independent of the environment the generator runs in.
pub fn config() -> &'static ts_rs::Config {
    static CONFIG: LazyLock<ts_rs::Config> = LazyLock::new(ts_rs::Config::new);
    &CONFIG
}

/// Requested checked-artifact operation.
pub enum GenerationMode {
    /// Replace changed generated artifacts.
    Write,
    /// Fail when any checked artifact differs.
    Check,
}

/// One repository-relative generated artifact.
pub struct Artifact {
    /// Path relative to the repository root.
    pub relative_path: &'static str,
    /// Full generated contents.
    pub contents: String,
}

/// Writes or checks the generated artifacts for one domain.
///
/// `generate_task` is the `effigy` task name stamped into failure messages, so
/// a check-mode diff tells the operator exactly what to rerun.
pub fn apply(
    domain: &str,
    generate_task: &str,
    mode: GenerationMode,
    artifacts: &[Artifact],
) -> Result<(), Box<dyn Error>> {
    for artifact in artifacts {
        if artifact.relative_path.ends_with("protocol.ts") {
            assert_protocol_references_resolve(domain, &artifact.contents)?;
        }
    }
    let root = repository_root();
    match mode {
        GenerationMode::Write => write_artifacts(&root, artifacts),
        GenerationMode::Check => check_artifacts(&root, domain, generate_task, artifacts),
    }
}

/// Refuse to emit a protocol module that names a type it never declares.
///
/// `check:bindings` only diffs generated bytes against the committed tree, so a
/// broken generator that agrees with itself still passes. Referenced types that
/// are not declared locally, imported via `import type`, or TypeScript builtins
/// fail here instead.
pub fn assert_protocol_references_resolve(
    domain: &str,
    contents: &str,
) -> Result<(), Box<dyn Error>> {
    let without_comments = strip_ts_comments(contents);
    let scanned = strip_ts_string_literals(&without_comments);
    let declared = declared_type_names(&scanned);
    let mut missing = BTreeSet::new();
    for name in type_name_references(&scanned) {
        if declared.contains(&name) || is_typescript_builtin_type(&name) {
            continue;
        }
        missing.insert(name);
    }
    if missing.is_empty() {
        Ok(())
    } else {
        Err(io::Error::other(format!(
            "{domain} protocol references undeclared types: {}. Add them to the \
             generator's declaration list (or stop referencing them) before \
             write/check can succeed.",
            missing.into_iter().collect::<Vec<_>>().join(", ")
        ))
        .into())
    }
}

/// Turns a `ts-rs` `type` declaration into an `export type` declaration.
pub fn exported_declaration(declaration: String) -> String {
    declaration
        .strip_prefix("type ")
        .map_or(declaration.clone(), |body| format!("export type {body}"))
}

/// Returns every discriminant value of a tagged union.
///
/// Fails when the declaration has no `{tag}` variants, so a generator that
/// drifts from the shape it claims to read stops here instead of emitting an
/// empty map.
pub fn tagged_variants(declaration: &str, tag: &str) -> Result<Vec<String>, Box<dyn Error>> {
    let marker = format!("\"{tag}\": \"");
    let values: Vec<_> = declaration
        .split(&marker)
        .skip(1)
        .filter_map(|suffix| suffix.split('"').next())
        .map(str::to_owned)
        .collect();
    if values.is_empty() {
        Err(io::Error::other(format!("generated declaration has no `{tag}` variants")).into())
    } else {
        Ok(values)
    }
}

/// The discriminant key of a tagged union, read from the declaration.
///
/// `ts-rs` quotes the tag key and its value and leaves every other key bare —
/// `{ "kind": "branch", branchId: BranchId, }`. So a quoted key with a quoted
/// value is the tag, and the tag is the one such key every arm shares.
///
/// Detected rather than supplied. Twelve domains do not agree on one key --
/// `kind`, `status` and `state` are all in use -- and a caller that has to
/// know which is another place the answer is written down twice.
pub fn detect_discriminant(declaration: &str) -> Option<String> {
    let declaration = strip_ts_comments(declaration);
    let (_, body) = declaration
        .trim()
        .strip_prefix("export type ")?
        .split_once(" = ")?;
    let mut shared: Option<BTreeSet<String>> = None;
    for arm in split_union_arms(body.trim().trim_end_matches(';')) {
        let keys: BTreeSet<String> = quoted_pairs(&arm).into_iter().map(|(key, _)| key).collect();
        shared = Some(match shared {
            None => keys,
            Some(previous) => previous.intersection(&keys).cloned().collect(),
        });
    }
    let shared = shared?;
    // Exactly one. Zero means no tag; more than one means two keys are quoted
    // literals in every arm, and guessing between them would be worse than
    // reporting the union as unreadable.
    (shared.len() == 1)
        .then(|| shared.into_iter().next())
        .flatten()
}

/// Every `"key": "value"` pair in one arm.
fn quoted_pairs(arm: &str) -> Vec<(String, String)> {
    let mut pairs = Vec::new();
    let mut rest = arm;
    while let Some(start) = rest.find('"') {
        let after = &rest[start + 1..];
        let Some(key_end) = after.find('"') else {
            break;
        };
        let key = &after[..key_end];
        let tail = after[key_end + 1..].trim_start();
        rest = &after[key_end + 1..];
        let Some(value) = tail.strip_prefix(':') else {
            continue;
        };
        let value = value.trim_start();
        let Some(value) = value.strip_prefix('"') else {
            continue;
        };
        let Some(value_end) = value.find('"') else {
            break;
        };
        pairs.push((key.to_owned(), value[..value_end].to_owned()));
        rest = &value[value_end + 1..];
    }
    pairs
}

/// Splits a tagged union into each variant's discriminant value and the keys
/// that variant allows, the discriminant included.
///
/// `tagged_variants` answers "which discriminants exist"; this answers "which
/// keys does each one allow", which is what a boundary check needs. The two
/// stay separate because the first feeds a `oneOf` over the discriminant and
/// the second feeds an `exact()` over the whole object, and a caller wants one
/// or the other rather than both.
///
/// The discriminant is included because `exact()` compares every key. Leaving
/// it out would reject every payload.
pub fn tagged_field_map(declaration: &str, tag: &str) -> Vec<(String, Vec<String>)> {
    let declaration = strip_ts_comments(declaration);
    let Some((_, body)) = declaration
        .trim()
        .strip_prefix("export type ")
        .and_then(|rest| rest.split_once(" = "))
    else {
        return Vec::new();
    };
    let marker = format!("\"{tag}\"");
    split_union_arms(body.trim().trim_end_matches(';'))
        .into_iter()
        .filter_map(|arm| {
            let arm = arm.trim().strip_prefix('{')?.strip_suffix('}')?;
            let fields = field_names(arm);
            // The discriminant's value, read from the arm rather than assumed
            // from position: `ts-rs` puts it first today and that is not a
            // guarantee worth depending on.
            let value = arm
                .split_once(&marker)?
                .1
                .split_once(':')?
                .1
                .trim()
                .trim_start_matches('"')
                .split('"')
                .next()?
                .to_owned();
            Some((value, fields))
        })
        .collect()
}

/// Splits a union body on `|` at brace depth zero.
///
/// An arm can hold a nested object or a generic carrying its own `|`, and a
/// naive split cuts such an arm in half -- yielding a short key list, which
/// then rejects valid payloads at the boundary instead of failing here.
/// `plain_object` refuses multi-brace bodies for exactly this reason; this is
/// the case it was refusing.
fn split_union_arms(body: &str) -> Vec<String> {
    let mut arms = Vec::new();
    let mut depth = 0_i32;
    let mut current = String::new();
    for character in body.chars() {
        match character {
            '{' | '<' | '(' | '[' => {
                depth += 1;
                current.push(character);
            }
            '}' | '>' | ')' | ']' => {
                depth -= 1;
                current.push(character);
            }
            '|' if depth == 0 => {
                arms.push(current.clone());
                current.clear();
            }
            _ => current.push(character),
        }
    }
    arms.push(current);
    arms
}

/// Returns every literal of a string-literal union.
///
/// Fails when the declaration has no variants, for the same reason
/// `tagged_variants` fails on an empty read.
pub fn string_union_variants(declaration: &str) -> Result<Vec<String>, Box<dyn Error>> {
    let body = declaration
        .split_once('=')
        .map(|(_, body)| body)
        .ok_or_else(|| io::Error::other("generated string union has no assignment"))?;
    let values: Vec<_> = body
        .trim()
        .trim_end_matches(';')
        .split('|')
        .map(str::trim)
        .filter_map(|value| value.strip_prefix('"')?.strip_suffix('"'))
        .map(str::to_owned)
        .collect();
    if values.is_empty() {
        Err(io::Error::other("generated string union has no variants").into())
    } else {
        Ok(values)
    }
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("binding crate must remain under crates/")
        .to_path_buf()
}

fn write_artifacts(root: &Path, artifacts: &[Artifact]) -> Result<(), Box<dyn Error>> {
    for artifact in artifacts {
        let path = root.join(artifact.relative_path);
        let parent = path
            .parent()
            .ok_or_else(|| io::Error::other("generated artifact has no parent"))?;
        fs::create_dir_all(parent)?;
        if fs::read_to_string(&path).ok().as_deref() != Some(artifact.contents.as_str()) {
            fs::write(&path, &artifact.contents)?;
            println!("wrote {}", artifact.relative_path);
        }
    }
    Ok(())
}

fn check_artifacts(
    root: &Path,
    domain: &str,
    generate_task: &str,
    artifacts: &[Artifact],
) -> Result<(), Box<dyn Error>> {
    let drifted: Vec<_> = artifacts
        .iter()
        .filter_map(|artifact| {
            let path = root.join(artifact.relative_path);
            (fs::read_to_string(path).ok().as_deref() != Some(artifact.contents.as_str()))
                .then_some(artifact.relative_path)
        })
        .collect();

    if drifted.is_empty() {
        println!("{domain} bindings and fixtures are current");
        Ok(())
    } else {
        Err(io::Error::other(format!(
            "generated {domain} artifacts drifted: {}; run `effigy {generate_task}`",
            drifted.join(", ")
        ))
        .into())
    }
}

/// One generated label map: a constant, the type indexing it, and its
/// entries.
pub struct LabelMap<'a> {
    /// The exported constant's name.
    pub constant: &'a str,
    /// The type imported from `protocol.ts` to key the record.
    pub import: &'a str,
    /// The type expression used as the record's key, which may index
    /// [`Self::import`] — a tagged union's discriminant is not itself
    /// importable.
    pub key_type: &'a str,
    /// `(wire name, label or label template)` pairs, from the Rust enum that
    /// owns the wording.
    pub entries: &'a [(&'a str, &'a str)],
}

/// Renders a generated TypeScript module of label maps.
///
/// Emitting these rather than letting the TypeScript tier keep its own is what
/// stops the two backends wording the same fact differently. Previously only
/// the Rust map failed to compile when a variant was added; the TypeScript one
/// silently returned `undefined`, and a webview rendered a blank.
///
/// Each map is typed `Record<key, string>`, so a variant added to the union and
/// missing from the map is a TypeScript error at the point of use rather than
/// a surprise at runtime.
#[must_use]
pub fn label_module(task: &str, maps: &[LabelMap<'_>]) -> String {
    let mut imports: Vec<&str> = maps.iter().map(|map| map.import).collect();
    imports.sort_unstable();
    imports.dedup();

    let mut rendered = format!("// @generated by `effigy {task}`; do not edit.\n");
    rendered
        .push_str("// Wording lives in Rust, on the enum that owns it. A label edited here is\n");
    rendered.push_str("// a label that disagrees with the native surface.\n\n");
    rendered.push_str("import type { ");
    rendered.push_str(&imports.join(", "));
    rendered.push_str(" } from \"./protocol.ts\";\n");

    for map in maps {
        rendered.push_str("\nexport const ");
        rendered.push_str(map.constant);
        rendered.push_str(": Record<");
        rendered.push_str(map.key_type);
        rendered.push_str(", string> = {\n");
        for (name, label) in map.entries {
            rendered.push_str("  ");
            rendered.push_str(&json_key(name));
            rendered.push_str(": ");
            rendered.push_str(&json_string(label));
            rendered.push_str(",\n");
        }
        rendered.push_str("};\n");
    }
    rendered
}

/// Renders the shared `{name}` interpolator used by templated label maps.
///
/// One substitution rule and deliberately not a template language, mirroring
/// `longhorn_config::render_label_template` exactly. An unknown placeholder is
/// left as written, so a mistake shows as `{typo}` on screen rather than a
/// hole that reads like intentional wording.
#[must_use]
pub fn label_template_renderer(task: &str) -> String {
    const BODY: &str = r#"// Mirrors `longhorn_config::render_label_template`. One substitution rule: a
// placeholder is a name in braces, and anything else is literal. An unknown
// placeholder is left as written, so a mistake shows as `{typo}` on screen
// rather than a hole that reads like intentional wording.

export function renderLabelTemplate(
  template: string,
  fields: Readonly<Record<string, string>>,
): string {
  return template.replace(/\{([^{}]*)\}/g, (match, name: string) =>
    Object.hasOwn(fields, name) ? fields[name]! : match,
  );
}
"#;

    format!("// @generated by `effigy {task}`; do not edit.\n{BODY}")
}

fn json_key(name: &str) -> String {
    if name
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || character == '_')
        && !name.starts_with(|character: char| character.is_ascii_digit())
    {
        name.to_owned()
    } else {
        json_string(name)
    }
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string to JSON cannot fail")
}

/// Unions with no discriminant to detect, and why each is allowed to have none.
///
/// Bridge's enums are externally tagged -- `"unsupported" | { "finite": .. }`
/// -- so the variant *is* the key and there is nothing to detect. That is a
/// modelling choice, not a defect, but it must be named: exempting it by
/// silence would look identical to the failure this check exists to catch.
///
/// Named per union rather than per domain, so a new bridge union has to be
/// considered rather than inheriting the pass.
const EXTERNALLY_TAGGED: &[&str] = &[
    "BridgeQueryOutcome",
    "BridgeCommandOutcome",
    "BridgeDeduplicationSupport",
    "BridgeJobTerminalOutcome",
    "BridgeCancellationOutcome",
    "BridgeServiceOutcome",
];

/// Renders the per-variant map beside the flat one.
///
/// Keyed by type name then by discriminant value. Beside rather than merged
/// into `field_map`: that one's values are `readonly string[]`, and a merged
/// shape would make every consumer narrow before using either.
///
/// # Panics
///
/// If a tagged union has no detectable discriminant and is not exempted. The
/// generator is a build step, so this fails the build: a union absent from the
/// map reads at the boundary as "no keys allowed", which is the silent failure
/// Cards 187 to 194 existed to remove. Reporting it and carrying on is what
/// this replaces.
#[must_use]
pub fn variant_field_map(task: &str, constant: &str, declarations: &[String]) -> String {
    let mut rendered = format!("// @generated by `effigy {task}`; do not edit.\n");
    rendered.push_str("// Allowed field names per tagged-union variant, from the Rust enums.\n");
    rendered.push_str("// Keyed by type, then by discriminant. The discriminant itself is in\n");
    rendered.push_str("// each list, because `exact()` compares every key.\n\n");
    rendered.push_str("export const ");
    rendered.push_str(constant);
    rendered.push_str(": Record<string, Record<string, readonly string[]>> = {\n");

    // The discriminant is emitted beside the map. One domain can use `kind`,
    // `status` and `state` -- `native-content` uses all three -- and a call
    // site that has to name the right one is a per-site chance to name the
    // wrong one.
    let mut discriminants =
        format!("\nexport const {constant}_DISCRIMINANTS: Record<string, string> = {{\n");
    let mut unreadable = Vec::new();
    for declaration in declarations {
        // `tagged_union_name` matches any `|` after the assignment, which a
        // plain record with a nullable field also has, and a string union has
        // too. Neither is a tagged union. Filter as `field_map` does -- reject
        // what `plain_object` accepts -- and additionally require a brace,
        // which every tagged union has and no string union does.
        if plain_object(declaration).is_some() || !declaration.contains('{') {
            continue;
        }
        let Some(name) = tagged_union_name(declaration) else {
            continue;
        };
        let tag = detect_discriminant(declaration);
        let variants = tag
            .as_deref()
            .map(|tag| tagged_field_map(declaration, tag))
            .unwrap_or_default();
        if variants.is_empty() {
            // No single key is a quoted literal in every arm, or the arms did
            // not split. Reported rather than skipped silently, because a
            // missing entry reads at the boundary as "no keys allowed".
            // Compared without type parameters: `tagged_union_name` keeps
            // them, and `BridgeQueryOutcome<S, D>` is the same union as
            // `BridgeQueryOutcome`.
            let bare = name.split_once('<').map_or(name.as_str(), |(base, _)| base);
            if !EXTERNALLY_TAGGED.contains(&bare) {
                unreadable.push(name);
            }
            continue;
        }
        rendered.push_str("  ");
        rendered.push_str(&json_string(&name));
        rendered.push_str(": {\n");
        for (value, fields) in variants {
            let fields: Vec<String> = fields.iter().map(|field| json_string(field)).collect();
            rendered.push_str("    ");
            rendered.push_str(&json_string(&value));
            rendered.push_str(": [");
            rendered.push_str(&fields.join(", "));
            rendered.push_str("],\n");
        }
        rendered.push_str("  },\n");
        if let Some(tag) = tag {
            discriminants.push_str("  ");
            discriminants.push_str(&json_string(&name));
            discriminants.push_str(": ");
            discriminants.push_str(&json_string(&tag));
            discriminants.push_str(",\n");
        }
    }
    rendered.push_str("};\n");
    discriminants.push_str("};\n");
    rendered.push_str(&discriminants);
    assert!(
        unreadable.is_empty(),
        "`effigy {task}`: no discriminant detected for {}. \
         Every arm must quote the same key -- `#[serde(tag = \"kind\")]` or \
         one of the other names `detect_discriminant` finds. If the union is \
         externally tagged by design, add it to `EXTERNALLY_TAGGED` with the \
         reason; do not leave it out of the map, because an absent entry reads \
         at the boundary as \"no keys allowed\".",
        unreadable.join(", ")
    );
    rendered
}

/// Emits the allowed field names for every plain object type in a domain.
///
/// Contract 010's boundary target requires rejecting unknown and missing
/// fields, and the nine packages that did not already have the *shape* to do
/// it — an error type, a `record()` helper, kind checks — only lacked the list
/// of keys. This emits that list so `record()` can take it, which is a much
/// smaller step than generating whole parsers and closes the asymmetry on its
/// own.
///
/// Only plain object declarations are emitted. A tagged union's fields depend
/// on its discriminant, so one flat list would be wrong for it; unions are
/// returned as skipped rather than guessed at, and the caller decides what to
/// say about them.
#[must_use]
pub fn field_map(task: &str, constant: &str, declarations: &[String]) -> (String, Vec<String>) {
    let mut rendered = format!("// @generated by `effigy {task}`; do not edit.\n");
    rendered.push_str("// Allowed field names per protocol type, from the Rust structs.\n");
    rendered.push_str("// A `record()` given one of these rejects unknown and missing keys —\n");
    rendered.push_str("// contract 010's Boundary Validation Target.\n\n");
    rendered.push_str("export const ");
    rendered.push_str(constant);
    rendered.push_str(": Record<string, readonly string[]> = {\n");

    let mut skipped = Vec::new();
    for declaration in declarations {
        let Some((name, body)) = plain_object(declaration) else {
            if let Some(name) = tagged_union_name(declaration) {
                skipped.push(name);
            }
            continue;
        };
        let fields: Vec<String> = field_names(&body)
            .into_iter()
            .map(|f| json_string(&f))
            .collect();
        rendered.push_str("  ");
        rendered.push_str(&json_string(&name));
        rendered.push_str(": [");
        rendered.push_str(&fields.join(", "));
        rendered.push_str("],\n");
    }
    rendered.push_str("};\n");
    (rendered, skipped)
}

/// Splits `export type Name = { .. };` into its name and body.
///
/// Returns `None` for anything whose fields are not one flat set: aliases,
/// string unions, and tagged unions. The last of those is the one that has to
/// be caught deliberately — `ts-rs` renders a tagged union as several brace
/// groups joined by `|`, its braces balance, and a naive balance check lets it
/// through and produces nonsense field names.
fn plain_object(declaration: &str) -> Option<(String, String)> {
    let declaration = strip_doc_comments(declaration);
    let rest = declaration.trim().strip_prefix("export type ")?;
    let (name, remainder) = rest.split_once(" = ")?;
    let body = remainder
        .trim()
        .strip_suffix(';')?
        .trim_end()
        .strip_prefix('{')?
        .strip_suffix('}')?;

    // One flat set means one brace group. Any brace inside the body is either
    // a further object or the next arm of a union, and neither has a single
    // answer to "which keys are allowed".
    if body.contains('{') || body.contains('}') {
        return None;
    }
    // A generic type carries its parameters in the declared name —
    // `BridgeProgressEvent<P>`. The allowed keys do not depend on them, and a
    // key with angle brackets is not a usable property name on the generated
    // record, so the parameters come off.
    let name = name.trim();
    let name = name.split_once('<').map_or(name, |(base, _)| base);
    Some((name.to_owned(), body.to_owned()))
}

/// Removes `/** .. */` blocks, which `ts-rs` emits from Rust doc comments.
///
/// They sit between fields and contain colons and commas, so a parser that
/// does not remove them reads prose as field names.
fn strip_doc_comments(declaration: &str) -> String {
    strip_ts_comments(declaration)
}

/// Drop `//` line comments and `/* ... */` block comments so prose is not
/// mistaken for type references.
fn strip_ts_comments(input: &str) -> String {
    let mut rendered = String::with_capacity(input.len());
    let mut chars = input.chars().peekable();
    while let Some(character) = chars.next() {
        if character == '/' && chars.peek() == Some(&'/') {
            let _ = chars.next();
            for inner in chars.by_ref() {
                if inner == '\n' {
                    rendered.push('\n');
                    break;
                }
            }
            continue;
        }
        if character == '/' && chars.peek() == Some(&'*') {
            let _ = chars.next();
            while let Some(inner) = chars.next() {
                if inner == '*' && chars.peek() == Some(&'/') {
                    let _ = chars.next();
                    break;
                }
            }
            continue;
        }
        rendered.push(character);
    }
    rendered
}

fn tagged_union_name(declaration: &str) -> Option<String> {
    let declaration = strip_doc_comments(declaration);
    let rest = declaration.trim().strip_prefix("export type ")?;
    let (name, remainder) = rest.split_once(" = ")?;
    remainder.contains('|').then(|| name.trim().to_owned())
}

/// Field names at brace depth zero, before the first colon of each.
///
/// Depth-aware because a field's own type can be an inline object or a
/// generic, and a comma inside either is not a field separator.
fn field_names(body: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut depth = 0_i32;
    let mut current = String::new();

    for character in body.chars() {
        match character {
            '{' | '<' | '(' => {
                depth += 1;
                current.push(character);
            }
            '}' | '>' | ')' => {
                depth -= 1;
                current.push(character);
            }
            // `ts-rs` separates fields with a comma when it renders a type
            // across lines and a semicolon when it renders one inline. Both
            // appear in the same generated module, and splitting on only one
            // silently yields a short field list — which then rejects valid
            // payloads at the boundary rather than failing loudly here.
            ',' | ';' if depth == 0 => {
                if let Some(name) = leading_name(&current) {
                    fields.push(name);
                }
                current.clear();
            }
            other => current.push(other),
        }
    }
    if let Some(name) = leading_name(&current) {
        fields.push(name);
    }
    fields
}

fn leading_name(part: &str) -> Option<String> {
    let trimmed = part.trim();
    if trimmed.is_empty() {
        return None;
    }
    let name = trimmed.split_once(':')?.0.trim();
    Some(name.trim_matches('"').to_owned())
}

fn strip_ts_string_literals(input: &str) -> String {
    let mut rendered = String::with_capacity(input.len());
    let mut chars = input.chars().peekable();
    while let Some(character) = chars.next() {
        if character != '"' {
            rendered.push(character);
            continue;
        }
        rendered.push(' ');
        while let Some(inner) = chars.next() {
            if inner == '\\' {
                let _ = chars.next();
                continue;
            }
            if inner == '"' {
                break;
            }
        }
        rendered.push(' ');
    }
    rendered
}

fn declared_type_names(contents: &str) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    let mut rest = contents;
    while let Some(index) = rest.find("export type ") {
        rest = &rest[index + "export type ".len()..];
        let name: String = rest
            .chars()
            .take_while(|character| character.is_ascii_alphanumeric() || *character == '_')
            .collect();
        if !name.is_empty() {
            names.insert(name);
        }
    }
    for name in imported_type_names(contents) {
        names.insert(name);
    }
    names
}

/// Names brought in by `import type { A, B } from "..."`.
fn imported_type_names(contents: &str) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    let mut rest = contents;
    while let Some(index) = rest.find("import type ") {
        rest = &rest[index + "import type ".len()..];
        let Some(open) = rest.find('{') else {
            continue;
        };
        let Some(close) = rest[open..].find('}') else {
            continue;
        };
        let list = &rest[open + 1..open + close];
        rest = &rest[open + close + 1..];
        for part in list.split(',') {
            let name =
                part.split_whitespace()
                    .next()
                    .unwrap_or("")
                    .trim_matches(|character: char| {
                        !character.is_ascii_alphanumeric() && character != '_'
                    });
            if !name.is_empty() {
                names.insert(name.to_owned());
            }
        }
    }
    names
}

fn type_name_references(contents: &str) -> BTreeSet<String> {
    let mut names = BTreeSet::new();
    let characters: Vec<char> = contents.chars().collect();
    let mut index = 0;
    while index < characters.len() {
        if !characters[index].is_ascii_uppercase() {
            index += 1;
            continue;
        }
        // Skip camelCase interiors (`hostInstanceId` must not yield `InstanceId`).
        if index > 0
            && (characters[index - 1].is_ascii_alphanumeric() || characters[index - 1] == '_')
        {
            index += 1;
            continue;
        }
        let start = index;
        index += 1;
        while index < characters.len()
            && (characters[index].is_ascii_alphanumeric() || characters[index] == '_')
        {
            index += 1;
        }
        let name: String = characters[start..index].iter().collect();
        if looks_like_type_name(&name) {
            names.insert(name);
        }
    }
    names
}

fn looks_like_type_name(name: &str) -> bool {
    name.chars()
        .next()
        .is_some_and(|character| character.is_ascii_uppercase())
        && name.chars().any(|character| character.is_ascii_lowercase())
}

fn is_typescript_builtin_type(name: &str) -> bool {
    matches!(
        name,
        "Array"
            | "ReadonlyArray"
            | "Record"
            | "Readonly"
            | "Partial"
            | "Required"
            | "Pick"
            | "Omit"
            | "Exclude"
            | "Extract"
            | "NonNullable"
            | "ReturnType"
            | "Promise"
            | "Map"
            | "Set"
            | "Date"
            | "Error"
            | "Uint8Array"
            | "ArrayBuffer"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Card 187. Three arm shapes in one union, because the unit variant is
    /// the one a hand-written map guesses at and the multi-field variant is
    /// the one it gets wrong.
    #[test]
    fn a_tagged_union_yields_each_variants_keys_including_the_discriminant() {
        let declaration = "\
export type Target = { \"kind\": \"undo\" } | { \"kind\": \"branch\", \
branchId: BranchId, } | { \"kind\": \"checkout\", branchId: BranchId, entryId: EntryId, };";
        let map = tagged_field_map(declaration, "kind");
        assert_eq!(
            map,
            vec![
                ("undo".to_owned(), vec!["kind".to_owned()]),
                (
                    "branch".to_owned(),
                    vec!["kind".to_owned(), "branchId".to_owned()]
                ),
                (
                    "checkout".to_owned(),
                    vec![
                        "kind".to_owned(),
                        "branchId".to_owned(),
                        "entryId".to_owned()
                    ]
                ),
            ]
        );
    }

    /// An arm holding a nested object must not be cut at the `|` inside it.
    /// A half-read arm yields a short key list, which rejects valid payloads
    /// at the boundary rather than failing here.
    #[test]
    fn a_nested_object_does_not_split_an_arm() {
        let declaration = "\
export type Result = { \"status\": \"ok\", detail: { code: number | null, }, } \
| { \"status\": \"failed\", reason: string, };";
        let map = tagged_field_map(declaration, "status");
        assert_eq!(
            map,
            vec![
                (
                    "ok".to_owned(),
                    vec!["status".to_owned(), "detail".to_owned()]
                ),
                (
                    "failed".to_owned(),
                    vec!["status".to_owned(), "reason".to_owned()]
                ),
            ]
        );
    }

    /// Doc prose sits between arms and holds colons and commas.
    #[test]
    fn documentation_between_arms_is_not_read_as_a_field() {
        let declaration = "\
export type Target = { \"kind\": \"undo\" } | { \"kind\": \"branch\", \
/** Explicit: a branch selection, chosen by the caller. */\n\
branchId: BranchId, };";
        let map = tagged_field_map(declaration, "kind");
        assert_eq!(
            map,
            vec![
                ("undo".to_owned(), vec!["kind".to_owned()]),
                (
                    "branch".to_owned(),
                    vec!["kind".to_owned(), "branchId".to_owned()]
                ),
            ]
        );
    }

    /// A plain record with a nullable field has a `|` and is not a union. The
    /// variant pass must skip it rather than report it unreadable.
    #[test]
    fn a_nullable_field_does_not_make_a_record_a_union() {
        // Not named `Record`: the rendered constant's own type annotation is
        // `Record<string, Record<string, readonly string[]>>`, so that name
        // would match the header rather than an entry.
        let declaration = "export type EntrySnapshot = { kindId: KindId | null, label: string, };";
        // No panic: a nullable field is not an arm, so there is no union to
        // find a discriminant for.
        let rendered = variant_field_map("test", "MAP", &[declaration.to_owned()]);
        assert!(!rendered.contains("EntrySnapshot"));
    }

    /// The check the milestone ends on. A union nobody can read is absent from
    /// the map, and an absent entry reads at the boundary as "no keys
    /// allowed" -- so it must stop the build rather than print a line.
    #[test]
    #[should_panic(expected = "no discriminant detected for Outcome")]
    fn an_unreadable_union_fails_the_build() {
        let declaration = "export type Outcome = { \"ok\": Ready } | { \"failed\": Cause };";
        let _ = variant_field_map("generate:test", "MAP", &[declaration.to_owned()]);
    }

    /// Bridge is externally tagged by design. The exemption is what keeps the
    /// check above from being suppressed wholesale the first time it fires.
    #[test]
    fn an_externally_tagged_union_is_exempted_by_name() {
        let declaration =
            "export type BridgeServiceOutcome = \"unsupported\" | { \"ready\": Service };";
        let rendered = variant_field_map("generate:bridge", "MAP", &[declaration.to_owned()]);
        assert!(!rendered.contains("BridgeServiceOutcome"));
    }

    /// The exemption is per union, not per domain, and generics are not part
    /// of the identity: `BridgeQueryOutcome<S, D>` is the exempted union, and
    /// a new bridge union is not.
    #[test]
    #[should_panic(expected = "BridgeUnnamedOutcome")]
    fn a_new_bridge_union_does_not_inherit_the_exemption() {
        let declarations = [
            "export type BridgeQueryOutcome<S, D> = \"pending\" | { \"ready\": S };".to_owned(),
            "export type BridgeUnnamedOutcome = \"pending\" | { \"ready\": D };".to_owned(),
        ];
        let _ = variant_field_map("generate:bridge", "MAP", &declarations);
    }

    /// Twelve domains use `kind`, `status` and `state`. Detecting beats being
    /// told, and the detector is what makes one pass enough.
    #[test]
    fn the_discriminant_is_detected_whatever_it_is_called() {
        for (tag, declaration) in [
            (
                "kind",
                "export type A = { \"kind\": \"one\" } | { \"kind\": \"two\", x: X, };",
            ),
            (
                "status",
                "export type B = { \"status\": \"ok\" } | { \"status\": \"bad\", why: string, };",
            ),
            (
                "state",
                "export type C = { \"state\": \"shown\" } | { \"state\": \"hidden\", at: N, };",
            ),
        ] {
            assert_eq!(detect_discriminant(declaration).as_deref(), Some(tag));
        }
    }

    /// A key quoted in one arm and absent from another is not the tag.
    #[test]
    fn a_key_missing_from_one_arm_is_not_the_discriminant() {
        let declaration =
            "export type A = { \"kind\": \"one\", \"extra\": \"here\" } | { \"kind\": \"two\" };";
        assert_eq!(detect_discriminant(declaration).as_deref(), Some("kind"));
    }

    #[test]
    fn protocol_with_undeclared_reference_fails() {
        let contents = "\
export type SurfaceId = string;\n\
export type SurfaceRecord = { id: SurfaceId, presentation: SurfacePresentation, };\n";
        let error = assert_protocol_references_resolve("surfaces", contents).unwrap_err();
        assert!(error.to_string().contains("SurfacePresentation"));
    }

    #[test]
    fn protocol_with_declared_reference_passes() {
        let contents = "\
export type SurfaceId = string;\n\
export type SurfacePresentation = { \"kind\": \"regional\" };\n\
export type SurfaceRecord = { id: SurfaceId, presentation: SurfacePresentation, };\n\
export const SURFACE_PROTOCOL_VERSION = 1 as const;\n";
        assert_protocol_references_resolve("surfaces", contents).unwrap();
    }

    #[test]
    fn builtins_and_string_literals_are_not_undeclared_types() {
        let contents = "\
export type RegionId = string;\n\
export type RegionState = { region_id: RegionId, panel_instance_ids: Array<RegionId>, };\n\
export type EmptyWindowPolicy = \"allow\" | \"reject\";\n";
        assert_protocol_references_resolve("surfaces", contents).unwrap();
    }

    #[test]
    fn line_comments_and_camel_case_fields_are_not_type_refs() {
        let contents = "\
// Rust serde types are the wire authority.\n\
// Wire-visible bounds. The Rust constants are the authority.\n\
export type HostInstanceId = string;\n\
export type BridgeRequestId = string;\n\
export type DomainAuthorityDescriptor = {\n\
  hostInstanceId: HostInstanceId,\n\
  requestId: BridgeRequestId,\n\
};\n";
        assert_protocol_references_resolve("bridge", contents).unwrap();
    }

    #[test]
    fn imported_types_count_as_resolved() {
        let contents = "\
import type { SurfaceId, SurfaceDocument } from \"@inflatable-cookie/longhorn/surfaces\";\n\
export type SurfaceSessionStartRequest = { surface_id: SurfaceId, document: SurfaceDocument, };\n";
        assert_protocol_references_resolve("surface-transfer", contents).unwrap();
    }
}
