use std::error::Error;

use longhorn_core::{
    HistoryEntryId, HistoryGroupId, HistoryId, HistoryKindId, HistoryPlanId, HistoryRevision,
};
use longhorn_history::HistoryAuthorityEpoch;
use longhorn_history_tree::{
    FORK_HISTORY_PROTOCOL_VERSION, ForkBranchId, ForkBranchPageCommand, ForkBranchPageSnapshot,
    ForkBranchRecord, ForkChangedEvent, ForkChangedKind, ForkEntryRecord,
    ForkHistoryProtocolVersion, ForkNavigationCommand, ForkNavigationReceiptProjection,
    ForkNavigationRejectionCode, ForkNavigationRejectionProjection, ForkNavigationResult,
    ForkNavigationTargetProjection, ForkPathPageCommand, ForkPathPageSnapshot,
    ForkPathTargetProjection, ForkProjectionPosition, ForkSnapshot, ForkSummaryProjection,
    MAXIMUM_FORK_PROJECTION_PAGE_SIZE,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, string_union_variants, tagged_variants,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/history-tree/src/generated/protocol.ts";
const GOLDEN_FIXTURE: &str = "fixtures/history-tree/protocol-v1.json";

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: render_protocol()?,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render()?,
        },
    ];
    apply("history-tree", "generate:history-tree", mode, &artifacts)
}

fn render_protocol() -> Result<String, Box<dyn Error>> {
    let position = ForkProjectionPosition::decl();
    let path_target = ForkPathTargetProjection::decl();
    let navigation_target = ForkNavigationTargetProjection::decl();
    let rejection_code = ForkNavigationRejectionCode::decl();
    let navigation_result = ForkNavigationResult::decl();
    let changed_kind = ForkChangedKind::decl();
    let declarations = [
        HistoryId::decl(),
        HistoryEntryId::decl(),
        HistoryGroupId::decl(),
        HistoryKindId::decl(),
        HistoryPlanId::decl(),
        HistoryRevision::decl(),
        HistoryAuthorityEpoch::decl(),
        ForkBranchId::decl(),
        ForkHistoryProtocolVersion::decl(),
        position.clone(),
        ForkSummaryProjection::decl(),
        ForkSnapshot::decl(),
        ForkEntryRecord::decl(),
        path_target.clone(),
        ForkPathPageCommand::decl(),
        ForkPathPageSnapshot::decl(),
        ForkBranchRecord::decl(),
        ForkBranchPageCommand::decl(),
        ForkBranchPageSnapshot::decl(),
        navigation_target.clone(),
        ForkNavigationCommand::decl(),
        ForkNavigationReceiptProjection::decl(),
        rejection_code.clone(),
        ForkNavigationRejectionProjection::decl(),
        navigation_result.clone(),
        changed_kind.clone(),
        ForkChangedEvent::decl(),
    ]
    .map(exported_declaration);

    Ok(format!(
        "// @generated by `effigy generate:history-tree`; do not edit.\n\
         // Rust serde types are authoritative. Product payloads are intentionally absent.\n\n\
         export const FORK_HISTORY_PROTOCOL_VERSION = {FORK_HISTORY_PROTOCOL_VERSION} as const;\n\
         export const MAXIMUM_FORK_HISTORY_PAGE_SIZE = {MAXIMUM_FORK_PROJECTION_PAGE_SIZE} as const;\n\
         export const FORK_HISTORY_ENTRY_POSITIONS = {} as const;\n\
         export const FORK_HISTORY_PATH_TARGETS = {} as const;\n\
         export const FORK_HISTORY_NAVIGATION_TARGETS = {} as const;\n\
         export const FORK_HISTORY_NAVIGATION_REJECTION_CODES = {} as const;\n\
         export const FORK_HISTORY_NAVIGATION_STATUSES = {} as const;\n\
         export const FORK_HISTORY_CHANGED_KINDS = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&string_union_variants(&position)?)?,
        serde_json::to_string(&tagged_variants(&path_target, "kind")?)?,
        serde_json::to_string(&tagged_variants(&navigation_target, "kind")?)?,
        serde_json::to_string(&string_union_variants(&rejection_code)?)?,
        serde_json::to_string(&tagged_variants(&navigation_result, "status")?)?,
        serde_json::to_string(&string_union_variants(&changed_kind)?)?,
        declarations.join("\n\n"),
    ))
}
