use std::error::Error;

use longhorn_core::{
    HistoryEntryId, HistoryGroupId, HistoryId, HistoryKindId, HistoryPlanId, HistoryRevision,
};
use longhorn_history::{HistoryAuthorityEpoch, HistoryRecordedAt};
use longhorn_history_tree::{
    FORK_HISTORY_PROTOCOL_VERSION, ForkBranchId, ForkBranchPageCommand, ForkBranchPageSnapshot,
    ForkBranchRecord, ForkChangedEvent, ForkChangedKind, ForkCheckpointId,
    ForkContinuationPageCommand, ForkContinuationPageSnapshot, ForkContinuationRecord,
    ForkDeleteContinuationCommand, ForkEntryRecord, ForkHistoryProtocolVersion,
    ForkNavigationCommand, ForkNavigationReceiptProjection, ForkNavigationRejectionCode,
    ForkNavigationRejectionProjection, ForkNavigationResult, ForkNavigationTargetProjection,
    ForkPathPageCommand, ForkPathPageSnapshot, ForkPathTargetProjection, ForkProjectionPosition,
    ForkPruneCommand, ForkPruneResult, ForkRemovalReceiptProjection, ForkRemovedEntryRecord,
    ForkSnapshot, ForkSummaryProjection, MAXIMUM_FORK_PROJECTION_PAGE_SIZE,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, field_map, string_union_variants,
    tagged_variants, variant_field_map,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/history-tree/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/history-tree/generated/fields.ts";
const GENERATED_VARIANT_FIELDS: &str =
    "packages/longhorn/src/history-tree/generated/variant-fields.ts";
const GOLDEN_FIXTURE: &str = "fixtures/history-tree/protocol-v1.json";

struct RenderedProtocol {
    contents: String,
    fields: String,
    variant_fields: String,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GENERATED_FIELDS,
            contents: protocol.fields,
        },
        Artifact {
            relative_path: GENERATED_VARIANT_FIELDS,
            contents: protocol.variant_fields,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render()?,
        },
    ];
    apply("history-tree", "generate:history-tree", mode, &artifacts)
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let position = ForkProjectionPosition::decl();
    let path_target = ForkPathTargetProjection::decl();
    let navigation_target = ForkNavigationTargetProjection::decl();
    let rejection_code = ForkNavigationRejectionCode::decl();
    let navigation_result = ForkNavigationResult::decl();
    let prune_result = ForkPruneResult::decl();
    let changed_kind = ForkChangedKind::decl();
    let declarations = [
        HistoryId::decl(),
        HistoryEntryId::decl(),
        HistoryGroupId::decl(),
        HistoryKindId::decl(),
        HistoryPlanId::decl(),
        HistoryRevision::decl(),
        HistoryAuthorityEpoch::decl(),
        ForkBranchId::decl(),
        ForkCheckpointId::decl(),
        ForkHistoryProtocolVersion::decl(),
        position.clone(),
        ForkSummaryProjection::decl(),
        ForkSnapshot::decl(),
        HistoryRecordedAt::decl(),
        ForkEntryRecord::decl(),
        path_target.clone(),
        ForkPathPageCommand::decl(),
        ForkPathPageSnapshot::decl(),
        ForkBranchRecord::decl(),
        ForkBranchPageCommand::decl(),
        ForkBranchPageSnapshot::decl(),
        ForkContinuationRecord::decl(),
        ForkContinuationPageCommand::decl(),
        ForkContinuationPageSnapshot::decl(),
        ForkDeleteContinuationCommand::decl(),
        ForkRemovedEntryRecord::decl(),
        ForkRemovalReceiptProjection::decl(),
        ForkPruneCommand::decl(),
        prune_result.clone(),
        navigation_target.clone(),
        ForkNavigationCommand::decl(),
        ForkNavigationReceiptProjection::decl(),
        rejection_code.clone(),
        ForkNavigationRejectionProjection::decl(),
        navigation_result.clone(),
        changed_kind.clone(),
        ForkChangedEvent::decl(),
    ]
    .map(exported_declaration);

    let contents = format!(
        "// @generated by `effigy generate:history-tree`; do not edit.\n\
         // Rust serde types are authoritative. Product payloads are intentionally absent.\n\n\
         export const FORK_HISTORY_PROTOCOL_VERSION = {FORK_HISTORY_PROTOCOL_VERSION} as const;\n\
         export const MAXIMUM_FORK_HISTORY_PAGE_SIZE = {MAXIMUM_FORK_PROJECTION_PAGE_SIZE} as const;\n\
         export const FORK_HISTORY_ENTRY_POSITIONS = {} as const;\n\
         export const FORK_HISTORY_PATH_TARGETS = {} as const;\n\
         export const FORK_HISTORY_NAVIGATION_TARGETS = {} as const;\n\
         export const FORK_HISTORY_NAVIGATION_REJECTION_CODES = {} as const;\n\
         export const FORK_HISTORY_NAVIGATION_STATUSES = {} as const;\n\
         export const FORK_HISTORY_CHANGED_KINDS = {} as const;\n\
         export const FORK_HISTORY_PRUNE_STATUSES = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&string_union_variants(&position)?)?,
        serde_json::to_string(&tagged_variants(&path_target, "kind")?)?,
        serde_json::to_string(&tagged_variants(&navigation_target, "kind")?)?,
        serde_json::to_string(&string_union_variants(&rejection_code)?)?,
        serde_json::to_string(&tagged_variants(&navigation_result, "status")?)?,
        serde_json::to_string(&string_union_variants(&changed_kind)?)?,
        serde_json::to_string(&tagged_variants(&prune_result, "status")?)?,
        declarations.join("\n\n"),
    );
    let (fields, skipped) = field_map(
        "generate:history-tree",
        "HISTORY_TREE_FIELDS",
        &declarations,
    );
    // The flat map skips every union, by design. Reporting that here would now
    // mislead: this domain's tagged unions are in the variant map below, and
    // its string unions are in the `*_POSITIONS`, `*_CODES` and `*_KINDS`
    // constants above. What is worth reporting is a union no map covers, and
    // that is what the variant pass returns.
    let _ = skipped;

    // One pass. The generator detects each union's discriminant rather than
    // being told: this domain's targets are tagged `kind` and its results
    // `status`, and a caller that has to know which is another place the
    // answer is written down twice.
    let (variant_fields, unreadable) = variant_field_map(
        "generate:history-tree",
        "HISTORY_TREE_VARIANT_FIELDS",
        &declarations,
    );
    if !unreadable.is_empty() {
        eprintln!(
            "[history-tree] tagged unions with no detectable discriminant: {}",
            unreadable.join(", ")
        );
    }
    Ok(RenderedProtocol {
        contents,
        fields,
        variant_fields,
    })
}
