use std::error::Error;

use longhorn_core::{
    HistoryEntryId, HistoryGroupId, HistoryId, HistoryKindId, HistoryPlanId, HistoryRevision,
};
use longhorn_history::{
    HISTORY_PROTOCOL_VERSION, HistoryAuthorityEpoch, HistoryBaselineProjection,
    HistoryChangedEvent, HistoryChangedKind, HistoryEntryRecord, HistoryNavigationCommand,
    HistoryNavigationDirectionProjection, HistoryNavigationPositionProjection,
    HistoryNavigationReceiptProjection, HistoryNavigationRejectionCode,
    HistoryNavigationRejectionProjection, HistoryNavigationResult,
    HistoryNavigationTargetProjection, HistoryPageCommand, HistoryPageSnapshot,
    HistoryProjectionPosition, HistoryProtocolMode, HistoryProtocolVersion, HistorySnapshot,
    HistorySummaryProjection,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, string_union_variants, tagged_variants,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/history/src/generated/protocol.ts";
const GOLDEN_FIXTURE: &str = "fixtures/history/protocol-v1.json";

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render()?,
        },
    ];
    apply("history", "generate:history", mode, &artifacts)
}

fn render_protocol() -> Result<String, Box<dyn Error>> {
    let mode = HistoryProtocolMode::decl();
    let position = HistoryProjectionPosition::decl();
    let target = HistoryNavigationTargetProjection::decl();
    let direction = HistoryNavigationDirectionProjection::decl();
    let rejection_code = HistoryNavigationRejectionCode::decl();
    let navigation_result = HistoryNavigationResult::decl();
    let changed_kind = HistoryChangedKind::decl();
    let declarations = [
        HistoryId::decl(),
        HistoryEntryId::decl(),
        HistoryGroupId::decl(),
        HistoryKindId::decl(),
        HistoryPlanId::decl(),
        HistoryRevision::decl(),
        HistoryProtocolVersion::decl(),
        HistoryAuthorityEpoch::decl(),
        mode.clone(),
        position.clone(),
        HistoryBaselineProjection::decl(),
        HistorySummaryProjection::decl(),
        HistorySnapshot::decl(),
        HistoryEntryRecord::decl(),
        HistoryPageCommand::decl(),
        HistoryPageSnapshot::decl(),
        target.clone(),
        HistoryNavigationCommand::decl(),
        direction.clone(),
        HistoryNavigationPositionProjection::decl(),
        HistoryNavigationReceiptProjection::decl(),
        rejection_code.clone(),
        HistoryNavigationRejectionProjection::decl(),
        navigation_result.clone(),
        changed_kind.clone(),
        HistoryChangedEvent::decl(),
    ]
    .map(exported_declaration);

    Ok(format!(
        "// @generated by `effigy generate:history`; do not edit.\n\
         // Rust serde types are the wire authority. Product payloads are intentionally absent.\n\n\
         export const HISTORY_PROTOCOL_VERSION = {HISTORY_PROTOCOL_VERSION} as const;\n\
         export const HISTORY_MODES = {} as const;\n\
         export const HISTORY_ENTRY_POSITIONS = {} as const;\n\
         export const HISTORY_NAVIGATION_TARGETS = {} as const;\n\
         export const HISTORY_NAVIGATION_DIRECTIONS = {} as const;\n\
         export const HISTORY_NAVIGATION_REJECTION_CODES = {} as const;\n\
         export const HISTORY_NAVIGATION_STATUSES = {} as const;\n\
         export const HISTORY_CHANGED_KINDS = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&string_union_variants(&mode)?)?,
        serde_json::to_string(&string_union_variants(&position)?)?,
        serde_json::to_string(&tagged_variants(&target, "kind")?)?,
        serde_json::to_string(&string_union_variants(&direction)?)?,
        serde_json::to_string(&string_union_variants(&rejection_code)?)?,
        serde_json::to_string(&tagged_variants(&navigation_result, "status")?)?,
        serde_json::to_string(&string_union_variants(&changed_kind)?)?,
        declarations.join("\n\n")
    ))
}
