use std::error::Error;

use longhorn_core::{
    HistoryEntryId, HistoryGroupId, HistoryId, HistoryKindId, HistoryPlanId, HistoryRevision,
    MAX_OPAQUE_ID_BYTES,
};
use longhorn_history::{
    HISTORY_PROTOCOL_VERSION, HistoryAuthorityEpoch, HistoryBaselineProjection,
    HistoryChangedEvent, HistoryChangedKind, HistoryEntryRecord, HistoryNavigationCommand,
    HistoryNavigationDirectionProjection, HistoryNavigationPositionProjection,
    HistoryNavigationReceiptProjection, HistoryNavigationRejectionCode,
    HistoryNavigationRejectionProjection, HistoryNavigationResult,
    HistoryNavigationTargetProjection, HistoryPageCommand, HistoryPageFloorProjection,
    HistoryPageSnapshot, HistoryProjectionPosition, HistoryProtocolMode, HistoryProtocolVersion,
    HistoryRecordedAt, HistorySnapshot, HistorySummaryProjection,
    MAXIMUM_HISTORY_PROJECTION_PAGE_SIZE,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, config, exported_declaration, field_map,
    string_union_variants, tagged_variants, variant_field_map,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/history/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/history/generated/fields.ts";
const GENERATED_VARIANT_FIELDS: &str = "packages/longhorn/src/history/generated/variant-fields.ts";
const GOLDEN_FIXTURE: &str = "fixtures/history/protocol-v1.json";

struct RenderedProtocol {
    contents: String,
    fields: String,
    variant_fields: String,
}

/// Generates or checks the history bindings and golden fixtures.
pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GENERATED_FIELDS,
            contents: protocol.fields,
        },
        Artifact {
            relative_path: GENERATED_VARIANT_FIELDS,
            contents: protocol.variant_fields,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render()?,
        },
    ];
    apply("history", "generate:history", mode, &artifacts)
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let mode = HistoryProtocolMode::decl(config());
    let position = HistoryProjectionPosition::decl(config());
    let target = HistoryNavigationTargetProjection::decl(config());
    let direction = HistoryNavigationDirectionProjection::decl(config());
    let rejection_code = HistoryNavigationRejectionCode::decl(config());
    let navigation_result = HistoryNavigationResult::decl(config());
    let changed_kind = HistoryChangedKind::decl(config());
    let page_floor = HistoryPageFloorProjection::decl(config());
    let declarations = [
        HistoryId::decl(config()),
        HistoryEntryId::decl(config()),
        HistoryGroupId::decl(config()),
        HistoryKindId::decl(config()),
        HistoryPlanId::decl(config()),
        HistoryRevision::decl(config()),
        HistoryRecordedAt::decl(config()),
        HistoryProtocolVersion::decl(config()),
        HistoryAuthorityEpoch::decl(config()),
        mode.clone(),
        position.clone(),
        HistoryBaselineProjection::decl(config()),
        HistorySummaryProjection::decl(config()),
        HistorySnapshot::decl(config()),
        HistoryEntryRecord::decl(config()),
        page_floor.clone(),
        HistoryPageCommand::decl(config()),
        HistoryPageSnapshot::decl(config()),
        target.clone(),
        HistoryNavigationCommand::decl(config()),
        direction.clone(),
        HistoryNavigationPositionProjection::decl(config()),
        HistoryNavigationReceiptProjection::decl(config()),
        rejection_code.clone(),
        HistoryNavigationRejectionProjection::decl(config()),
        navigation_result.clone(),
        changed_kind.clone(),
        HistoryChangedEvent::decl(config()),
    ]
    .map(exported_declaration);

    let contents = format!(
        "// @generated by `effigy generate:history`; do not edit.\n\
         // Rust serde types are the wire authority. Product payloads are intentionally absent.\n\n\
         export const HISTORY_PROTOCOL_VERSION = {HISTORY_PROTOCOL_VERSION} as const;\n\
         export const HISTORY_MAXIMUM_OPAQUE_ID_BYTES = {MAX_OPAQUE_ID_BYTES} as const;\n\
         export const HISTORY_MAXIMUM_PROJECTION_PAGE_SIZE = {MAXIMUM_HISTORY_PROJECTION_PAGE_SIZE} as const;\n\
         export const HISTORY_MODES = {} as const;\n\
         export const HISTORY_ENTRY_POSITIONS = {} as const;\n\
         export const HISTORY_PAGE_FLOORS = {} as const;\n\
         export const HISTORY_NAVIGATION_TARGETS = {} as const;\n\
         export const HISTORY_NAVIGATION_DIRECTIONS = {} as const;\n\
         export const HISTORY_NAVIGATION_REJECTION_CODES = {} as const;\n\
         export const HISTORY_NAVIGATION_STATUSES = {} as const;\n\
         export const HISTORY_CHANGED_KINDS = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&string_union_variants(&mode)?)?,
        serde_json::to_string(&string_union_variants(&position)?)?,
        serde_json::to_string(&tagged_variants(&page_floor, "kind")?)?,
        serde_json::to_string(&tagged_variants(&target, "kind")?)?,
        serde_json::to_string(&string_union_variants(&direction)?)?,
        serde_json::to_string(&string_union_variants(&rejection_code)?)?,
        serde_json::to_string(&tagged_variants(&navigation_result, "status")?)?,
        serde_json::to_string(&string_union_variants(&changed_kind)?)?,
        declarations.join("\n\n")
    );
    let (fields, _skipped) = field_map("generate:history", "HISTORY_FIELDS", &declarations);

    let variant_fields =
        variant_field_map("generate:history", "HISTORY_VARIANT_FIELDS", &declarations);

    Ok(RenderedProtocol {
        contents,
        fields,
        variant_fields,
    })
}
