use std::error::Error;

use longhorn_core::{
    LayoutRequestId, LayoutSchemaId, PanelDefinitionId, PanelInstanceId, RegionFamilyId, RegionId,
    SizingSlotId, SurfaceId, SurfaceRevision, WindowId,
};
use longhorn_surfaces::{
    EmptyRegionPolicy, LAYOUT_PROTOCOL_VERSION, LayoutLimits, LayoutMutationCommand,
    LayoutMutationOutcome, LayoutMutationReceipt, LayoutMutationRejection,
    LayoutMutationRejectionCode, LayoutMutationRequest, LayoutRatio, LayoutSchemaDefinition,
    PanelDefinition, PanelInstance, PanelInstancePolicy, ParticipatingWindow, PlacementSelector,
    RegionDefinition, RegionState, RegionVisibility, RegionVisibilityState, SizingSlotDefinition,
    SizingSlotState, SurfaceDocument, SurfaceHostPreference, SurfacePresentation, SurfaceRecord,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, config, exported_declaration, string_union_variants,
    tagged_variants,
};

mod conformance;
pub(crate) mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/layout/generated/protocol.ts";
const GOLDEN_FIXTURE: &str = "fixtures/layout/protocol-v1.json";

struct RenderedProtocol {
    contents: String,
    rejection_codes: Vec<String>,
}

/// Generates or checks the layout bindings and golden fixtures.
pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let mut artifacts = vec![
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render(&protocol.rejection_codes)?,
        },
    ];
    artifacts.extend(
        conformance::render()?
            .into_iter()
            .map(|(relative_path, contents)| Artifact {
                relative_path,
                contents,
            }),
    );

    apply("layout", "generate:layout", mode, &artifacts)
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let command_declaration = LayoutMutationCommand::decl(config());
    let outcome_declaration = LayoutMutationOutcome::decl(config());
    let rejection_declaration = LayoutMutationRejectionCode::decl(config());
    let command_kinds = tagged_variants(&command_declaration, "kind")?;
    let outcome_kinds = tagged_variants(&outcome_declaration, "kind")?;
    let rejection_codes = string_union_variants(&rejection_declaration)?;
    let declarations = [
        LayoutSchemaId::decl(config()),
        SurfaceId::decl(config()),
        RegionId::decl(config()),
        RegionFamilyId::decl(config()),
        SizingSlotId::decl(config()),
        PanelDefinitionId::decl(config()),
        PanelInstanceId::decl(config()),
        LayoutRequestId::decl(config()),
        SurfaceRevision::decl(config()),
        LayoutRatio::decl(config()),
        LayoutLimits::decl(config()),
        EmptyRegionPolicy::decl(config()),
        RegionDefinition::decl(config()),
        SizingSlotDefinition::decl(config()),
        LayoutSchemaDefinition::decl(config()),
        PlacementSelector::decl(config()),
        PanelInstancePolicy::decl(config()),
        PanelDefinition::decl(config()),
        PanelInstance::decl(config()),
        WindowId::decl(config()),
        RegionState::decl(config()),
        SizingSlotState::decl(config()),
        SurfaceHostPreference::decl(config()),
        SurfacePresentation::decl(config()),
        SurfaceRecord::decl(config()),
        ParticipatingWindow::decl(config()),
        SurfaceDocument::decl(config()),
        RegionVisibilityState::decl(config()),
        RegionVisibility::decl(config()),
        command_declaration,
        LayoutMutationRequest::decl(config()),
        outcome_declaration,
        LayoutMutationReceipt::decl(config()),
        rejection_declaration,
        LayoutMutationRejection::decl(config()),
    ];
    let declarations = declarations.map(exported_declaration);
    let command_kinds_json = serde_json::to_string(&command_kinds)?;
    let outcome_kinds_json = serde_json::to_string(&outcome_kinds)?;
    let rejection_codes_json = serde_json::to_string(&rejection_codes)?;

    let contents = format!(
        "// @generated by `effigy generate:layout`; do not edit.\n\
         // Rust serde types are the wire authority.\n\n\
         export const LAYOUT_PROTOCOL_VERSION = {LAYOUT_PROTOCOL_VERSION} as const;\n\
         export const LAYOUT_MUTATION_COMMAND_KINDS = {command_kinds_json} as const;\n\
         export const LAYOUT_MUTATION_OUTCOME_KINDS = {outcome_kinds_json} as const;\n\
         export const LAYOUT_MUTATION_REJECTION_CODES = {rejection_codes_json} as const;\n\n\
         {}\n",
        declarations.join("\n\n")
    );
    Ok(RenderedProtocol {
        contents,
        rejection_codes,
    })
}
