use std::error::Error;

use longhorn_core::{
    LayoutContainerId, LayoutRequestId, LayoutRevision, LayoutSchemaId, PanelDefinitionId,
    PanelInstanceId, RegionFamilyId, RegionId, SizingSlotId,
};
use longhorn_layout::{
    EmptyRegionPolicy, LAYOUT_PROTOCOL_VERSION, LayoutContainer, LayoutDocument, LayoutLimits,
    LayoutMutationCommand, LayoutMutationOutcome, LayoutMutationReceipt, LayoutMutationRejection,
    LayoutMutationRejectionCode, LayoutMutationRequest, LayoutRatio, LayoutSchemaDefinition,
    PanelDefinition, PanelInstance, PanelInstancePolicy, PlacementSelector, RegionDefinition,
    RegionState, RegionVisibility, RegionVisibilityState, SizingSlotDefinition, SizingSlotState,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, string_union_variants, tagged_variants,
};

mod conformance;
mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/layout/generated/protocol.ts";
const GOLDEN_FIXTURE: &str = "fixtures/layout/protocol-v1.json";

struct RenderedProtocol {
    contents: String,
    rejection_codes: Vec<String>,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let mut artifacts = vec![
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render(&protocol.rejection_codes)?,
        },
    ];
    artifacts.extend(
        conformance::render()?
            .into_iter()
            .map(|(relative_path, contents)| Artifact {
                relative_path,
                contents,
            }),
    );

    apply("layout", "generate:layout", mode, &artifacts)
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let command_declaration = LayoutMutationCommand::decl();
    let outcome_declaration = LayoutMutationOutcome::decl();
    let rejection_declaration = LayoutMutationRejectionCode::decl();
    let command_kinds = tagged_variants(&command_declaration, "kind")?;
    let outcome_kinds = tagged_variants(&outcome_declaration, "kind")?;
    let rejection_codes = string_union_variants(&rejection_declaration)?;
    let declarations = [
        LayoutSchemaId::decl(),
        LayoutContainerId::decl(),
        RegionId::decl(),
        RegionFamilyId::decl(),
        SizingSlotId::decl(),
        PanelDefinitionId::decl(),
        PanelInstanceId::decl(),
        LayoutRequestId::decl(),
        LayoutRevision::decl(),
        LayoutRatio::decl(),
        LayoutLimits::decl(),
        EmptyRegionPolicy::decl(),
        RegionDefinition::decl(),
        SizingSlotDefinition::decl(),
        LayoutSchemaDefinition::decl(),
        PlacementSelector::decl(),
        PanelInstancePolicy::decl(),
        PanelDefinition::decl(),
        PanelInstance::decl(),
        RegionState::decl(),
        SizingSlotState::decl(),
        LayoutContainer::decl(),
        LayoutDocument::decl(),
        RegionVisibilityState::decl(),
        RegionVisibility::decl(),
        command_declaration,
        LayoutMutationRequest::decl(),
        outcome_declaration,
        LayoutMutationReceipt::decl(),
        rejection_declaration,
        LayoutMutationRejection::decl(),
    ];
    let declarations = declarations.map(exported_declaration);
    let command_kinds_json = serde_json::to_string(&command_kinds)?;
    let outcome_kinds_json = serde_json::to_string(&outcome_kinds)?;
    let rejection_codes_json = serde_json::to_string(&rejection_codes)?;

    let contents = format!(
        "// @generated by `effigy generate:layout`; do not edit.\n\
         // Rust serde types are the wire authority.\n\n\
         export const LAYOUT_PROTOCOL_VERSION = {LAYOUT_PROTOCOL_VERSION} as const;\n\
         export const LAYOUT_MUTATION_COMMAND_KINDS = {command_kinds_json} as const;\n\
         export const LAYOUT_MUTATION_OUTCOME_KINDS = {outcome_kinds_json} as const;\n\
         export const LAYOUT_MUTATION_REJECTION_CODES = {rejection_codes_json} as const;\n\n\
         {}\n",
        declarations.join("\n\n")
    );
    Ok(RenderedProtocol {
        contents,
        rejection_codes,
    })
}
