use std::{
    env,
    error::Error,
    fs, io,
    path::{Path, PathBuf},
};

use longhorn_core::{
    LayoutContainerId, LayoutRequestId, LayoutRevision, LayoutSchemaId, PanelDefinitionId,
    PanelInstanceId, RegionFamilyId, RegionId, SizingSlotId,
};
use longhorn_layout::{
    EmptyRegionPolicy, LAYOUT_PROTOCOL_VERSION, LayoutContainer, LayoutDocument, LayoutLimits,
    LayoutMutationCommand, LayoutMutationOutcome, LayoutMutationReceipt, LayoutMutationRejection,
    LayoutMutationRejectionCode, LayoutMutationRequest, LayoutRatio, LayoutSchemaDefinition,
    PanelDefinition, PanelInstance, PanelInstancePolicy, PlacementSelector, RegionDefinition,
    RegionState, RegionVisibility, RegionVisibilityState, SizingSlotDefinition, SizingSlotState,
};
use ts_rs::TS;

mod conformance;
mod fixture;

const GENERATED_PROTOCOL: &str = "packages/layout/src/generated/protocol.ts";
const GOLDEN_FIXTURE: &str = "fixtures/layout/protocol-v1.json";

pub enum GenerationMode {
    Write,
    Check,
}

struct Artifact {
    relative_path: &'static str,
    contents: String,
}

struct RenderedProtocol {
    contents: String,
    rejection_codes: Vec<String>,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let root = repository_root();
    let protocol = render_protocol()?;
    let mut artifacts = vec![
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render(&protocol.rejection_codes)?,
        },
    ];
    artifacts.extend(
        conformance::render()?
            .into_iter()
            .map(|(relative_path, contents)| Artifact {
                relative_path,
                contents,
            }),
    );

    match mode {
        GenerationMode::Write => write_artifacts(&root, &artifacts),
        GenerationMode::Check => check_artifacts(&root, &artifacts),
    }
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("binding crate must remain under crates/")
        .to_path_buf()
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let command_declaration = LayoutMutationCommand::decl();
    let outcome_declaration = LayoutMutationOutcome::decl();
    let rejection_declaration = LayoutMutationRejectionCode::decl();
    let command_kinds = tagged_variants(&command_declaration, "kind")?;
    let outcome_kinds = tagged_variants(&outcome_declaration, "kind")?;
    let rejection_codes = string_union_variants(&rejection_declaration)?;
    let declarations = [
        LayoutSchemaId::decl(),
        LayoutContainerId::decl(),
        RegionId::decl(),
        RegionFamilyId::decl(),
        SizingSlotId::decl(),
        PanelDefinitionId::decl(),
        PanelInstanceId::decl(),
        LayoutRequestId::decl(),
        LayoutRevision::decl(),
        LayoutRatio::decl(),
        LayoutLimits::decl(),
        EmptyRegionPolicy::decl(),
        RegionDefinition::decl(),
        SizingSlotDefinition::decl(),
        LayoutSchemaDefinition::decl(),
        PlacementSelector::decl(),
        PanelInstancePolicy::decl(),
        PanelDefinition::decl(),
        PanelInstance::decl(),
        RegionState::decl(),
        SizingSlotState::decl(),
        LayoutContainer::decl(),
        LayoutDocument::decl(),
        RegionVisibilityState::decl(),
        RegionVisibility::decl(),
        command_declaration,
        LayoutMutationRequest::decl(),
        outcome_declaration,
        LayoutMutationReceipt::decl(),
        rejection_declaration,
        LayoutMutationRejection::decl(),
    ];
    let declarations = declarations.map(|declaration| {
        declaration
            .strip_prefix("type ")
            .map_or(declaration.clone(), |body| format!("export type {body}"))
    });
    let command_kinds_json = serde_json::to_string(&command_kinds)?;
    let outcome_kinds_json = serde_json::to_string(&outcome_kinds)?;
    let rejection_codes_json = serde_json::to_string(&rejection_codes)?;

    let contents = format!(
        "// @generated by `effigy generate:layout`; do not edit.\n\
         // Rust serde types are the wire authority.\n\n\
         export const LAYOUT_PROTOCOL_VERSION = {LAYOUT_PROTOCOL_VERSION} as const;\n\
         export const LAYOUT_MUTATION_COMMAND_KINDS = {command_kinds_json} as const;\n\
         export const LAYOUT_MUTATION_OUTCOME_KINDS = {outcome_kinds_json} as const;\n\
         export const LAYOUT_MUTATION_REJECTION_CODES = {rejection_codes_json} as const;\n\n\
         {}\n",
        declarations.join("\n\n")
    );
    Ok(RenderedProtocol {
        contents,
        rejection_codes,
    })
}

fn tagged_variants(declaration: &str, tag: &str) -> Result<Vec<String>, Box<dyn Error>> {
    let marker = format!("\"{tag}\": \"");
    let values: Vec<_> = declaration
        .split(&marker)
        .skip(1)
        .filter_map(|suffix| suffix.split('"').next())
        .map(str::to_owned)
        .collect();
    if values.is_empty() {
        Err(io::Error::other(format!("generated declaration has no `{tag}` variants")).into())
    } else {
        Ok(values)
    }
}

fn string_union_variants(declaration: &str) -> Result<Vec<String>, Box<dyn Error>> {
    let body = declaration
        .split_once('=')
        .map(|(_, body)| body)
        .ok_or_else(|| io::Error::other("generated string union has no assignment"))?;
    let values: Vec<_> = body
        .trim()
        .trim_end_matches(';')
        .split('|')
        .map(str::trim)
        .filter_map(|value| value.strip_prefix('"')?.strip_suffix('"'))
        .map(str::to_owned)
        .collect();
    if values.is_empty() {
        Err(io::Error::other("generated string union has no variants").into())
    } else {
        Ok(values)
    }
}

fn write_artifacts(root: &Path, artifacts: &[Artifact]) -> Result<(), Box<dyn Error>> {
    for artifact in artifacts {
        let path = root.join(artifact.relative_path);
        let parent = path
            .parent()
            .ok_or_else(|| io::Error::other("generated artifact has no parent"))?;
        fs::create_dir_all(parent)?;
        if fs::read_to_string(&path).ok().as_deref() != Some(artifact.contents.as_str()) {
            fs::write(&path, &artifact.contents)?;
            println!("wrote {}", artifact.relative_path);
        }
    }
    Ok(())
}

fn check_artifacts(root: &Path, artifacts: &[Artifact]) -> Result<(), Box<dyn Error>> {
    let drifted: Vec<_> = artifacts
        .iter()
        .filter_map(|artifact| {
            let path = root.join(artifact.relative_path);
            (fs::read_to_string(path).ok().as_deref() != Some(artifact.contents.as_str()))
                .then_some(artifact.relative_path)
        })
        .collect();

    if drifted.is_empty() {
        println!("layout bindings and fixtures are current");
        Ok(())
    } else {
        Err(io::Error::other(format!(
            "generated layout artifacts drifted: {}; run `effigy generate:layout`",
            drifted.join(", ")
        ))
        .into())
    }
}
