use std::error::Error;

use longhorn_licence::{
    HeldLicenceProjection, LICENCE_PROTOCOL_VERSION, LicenceActivateCommand, LicenceChangedEvent,
    LicenceChangedKind, LicenceCredentialProjection, LicenceDeactivateCommand,
    LicenceEntitlementProjection, LicenceOutcomeProjection, LicenceProtocolVersion,
    LicenceRefreshCommand, LicenceRejectionCode, LicenceSnapshot, LicenceTrustBasisProjection,
    LicenceUsabilityProjection, Timestamp,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, field_map, string_union_variants,
    tagged_variants, variant_field_map,
};

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/licence/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/licence/generated/fields.ts";
const GENERATED_VARIANT_FIELDS: &str = "packages/longhorn/src/licence/generated/variant-fields.ts";

struct RenderedProtocol {
    contents: String,
    fields: String,
    variant_fields: String,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    apply(
        "licence",
        "generate:licence",
        mode,
        &[
            Artifact {
                relative_path: GENERATED_PROTOCOL,
                contents: protocol.contents,
            },
            Artifact {
                relative_path: GENERATED_FIELDS,
                contents: protocol.fields,
            },
            Artifact {
                relative_path: GENERATED_VARIANT_FIELDS,
                contents: protocol.variant_fields,
            },
        ],
    )
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let usability = LicenceUsabilityProjection::decl();
    let trust_basis = LicenceTrustBasisProjection::decl();
    let credential = LicenceCredentialProjection::decl();
    let rejection_code = LicenceRejectionCode::decl();
    let outcome = LicenceOutcomeProjection::decl();
    let changed_kind = LicenceChangedKind::decl();

    let declarations = [
        LicenceProtocolVersion::decl(),
        Timestamp::decl(),
        usability.clone(),
        trust_basis.clone(),
        LicenceEntitlementProjection::decl(),
        HeldLicenceProjection::decl(),
        LicenceSnapshot::decl(),
        credential.clone(),
        LicenceActivateCommand::decl(),
        LicenceDeactivateCommand::decl(),
        LicenceRefreshCommand::decl(),
        rejection_code.clone(),
        outcome.clone(),
        changed_kind.clone(),
        LicenceChangedEvent::decl(),
    ]
    .map(exported_declaration);

    let contents = format!(
        "// @generated by `effigy generate:licence`; do not edit.\n\
         // Rust serde types are the wire authority. Entitlements are opaque\n\
         // ids: Longhorn answers \"entitled?\" and enumerates no features.\n\n\
         export const LICENCE_PROTOCOL_VERSION = {LICENCE_PROTOCOL_VERSION} as const;\n\
         export const LICENCE_USABILITY_STATES = {} as const;\n\
         export const LICENCE_TRUST_BASIS_KINDS = {} as const;\n\
         export const LICENCE_CREDENTIAL_KINDS = {} as const;\n\
         export const LICENCE_REJECTION_CODES = {} as const;\n\
         export const LICENCE_OUTCOME_STATUSES = {} as const;\n\
         export const LICENCE_CHANGED_KINDS = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&tagged_variants(&usability, "state")?)?,
        serde_json::to_string(&tagged_variants(&trust_basis, "kind")?)?,
        serde_json::to_string(&tagged_variants(&credential, "kind")?)?,
        serde_json::to_string(&string_union_variants(&rejection_code)?)?,
        serde_json::to_string(&tagged_variants(&outcome, "status")?)?,
        serde_json::to_string(&string_union_variants(&changed_kind)?)?,
        declarations.join("\n\n"),
    );

    let (fields, _skipped) = field_map("generate:licence", "LICENCE_FIELDS", &declarations);
    let variant_fields =
        variant_field_map("generate:licence", "LICENCE_VARIANT_FIELDS", &declarations);

    Ok(RenderedProtocol {
        contents,
        fields,
        variant_fields,
    })
}
