use std::error::Error;

use longhorn_core::{
    NotificationActionReferenceId, NotificationAuthorityId, NotificationCauseId, NotificationId,
    NotificationLedgerRevision, NotificationProducerToken, NotificationReplacementKey,
    NotificationRequestId, NotificationSourceId,
};
use longhorn_notifications::{
    NOTIFICATION_PROTOCOL_VERSION, NotificationActionProjection, NotificationAuthorityProjection,
    NotificationChangedEvent, NotificationChangedKind, NotificationClearTargetProjection,
    NotificationDraftProjection, NotificationLedgerLimitsProjection, NotificationMutationCommand,
    NotificationMutationReceiptProjection, NotificationMutationResult, NotificationPageProjection,
    NotificationProtocolVersion, NotificationReadStateProjection, NotificationRecordProjection,
    NotificationRejection, NotificationRejectionCode, NotificationRemovalProjection,
    NotificationRemovalReasonProjection, NotificationRetentionClassProjection,
    NotificationSeverityProjection, NotificationSnapshot, NotificationSnapshotQuery,
    NotificationSnapshotResponse,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, string_union_variants, tagged_variants,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/notifications/src/generated/protocol.ts";
const GOLDEN_FIXTURE: &str = "fixtures/notifications/protocol-v1.json";

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    apply(
        "notifications",
        "generate:notifications",
        mode,
        &[
            Artifact {
                relative_path: GENERATED_PROTOCOL,
                contents: render_protocol()?,
            },
            Artifact {
                relative_path: GOLDEN_FIXTURE,
                contents: fixture::render()?,
            },
        ],
    )
}

fn render_protocol() -> Result<String, Box<dyn Error>> {
    let severity = NotificationSeverityProjection::decl();
    let read_state = NotificationReadStateProjection::decl();
    let retention = NotificationRetentionClassProjection::decl();
    let clear_target = NotificationClearTargetProjection::decl();
    let mutation = NotificationMutationCommand::decl();
    let removal_reason = NotificationRemovalReasonProjection::decl();
    let receipt = NotificationMutationReceiptProjection::decl();
    let rejection_code = NotificationRejectionCode::decl();
    let result = NotificationMutationResult::decl();
    let changed_kind = NotificationChangedKind::decl();
    let declarations = [
        NotificationActionReferenceId::decl(),
        NotificationAuthorityId::decl(),
        NotificationCauseId::decl(),
        NotificationId::decl(),
        NotificationLedgerRevision::decl(),
        NotificationProducerToken::decl(),
        NotificationReplacementKey::decl(),
        NotificationRequestId::decl(),
        NotificationSourceId::decl(),
        NotificationProtocolVersion::decl(),
        NotificationAuthorityProjection::decl(),
        severity.clone(),
        read_state.clone(),
        retention.clone(),
        NotificationActionProjection::decl(),
        NotificationDraftProjection::decl(),
        NotificationRecordProjection::decl(),
        NotificationLedgerLimitsProjection::decl(),
        NotificationPageProjection::decl(),
        NotificationSnapshot::decl(),
        NotificationSnapshotQuery::decl(),
        NotificationSnapshotResponse::decl(),
        clear_target.clone(),
        mutation.clone(),
        removal_reason.clone(),
        NotificationRemovalProjection::decl(),
        receipt.clone(),
        rejection_code.clone(),
        NotificationRejection::decl(),
        result.clone(),
        changed_kind.clone(),
        NotificationChangedEvent::decl(),
    ]
    .map(exported_declaration);

    Ok(format!(
        "// @generated by `effigy generate:notifications`; do not edit.\n\
         // Rust serde types are the wire authority. Executable actions are intentionally absent.\n\n\
         export const NOTIFICATION_PROTOCOL_VERSION = {NOTIFICATION_PROTOCOL_VERSION} as const;\n\
         export const NOTIFICATION_SEVERITIES = {} as const;\n\
         export const NOTIFICATION_READ_STATES = {} as const;\n\
         export const NOTIFICATION_RETENTION_CLASSES = {} as const;\n\
         export const NOTIFICATION_CLEAR_TARGET_KINDS = {} as const;\n\
         export const NOTIFICATION_MUTATION_KINDS = {} as const;\n\
         export const NOTIFICATION_REMOVAL_REASONS = {} as const;\n\
         export const NOTIFICATION_RECEIPT_KINDS = {} as const;\n\
         export const NOTIFICATION_REJECTION_CODES = {} as const;\n\
         export const NOTIFICATION_MUTATION_STATUSES = {} as const;\n\
         export const NOTIFICATION_CHANGED_KINDS = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&string_union_variants(&severity)?)?,
        serde_json::to_string(&string_union_variants(&read_state)?)?,
        serde_json::to_string(&string_union_variants(&retention)?)?,
        serde_json::to_string(&tagged_variants(&clear_target, "kind")?)?,
        serde_json::to_string(&tagged_variants(&mutation, "kind")?)?,
        serde_json::to_string(&string_union_variants(&removal_reason)?)?,
        serde_json::to_string(&tagged_variants(&receipt, "kind")?)?,
        serde_json::to_string(&string_union_variants(&rejection_code)?)?,
        serde_json::to_string(&tagged_variants(&result, "status")?)?,
        serde_json::to_string(&string_union_variants(&changed_kind)?)?,
        declarations.join("\n\n")
    ))
}
