use std::error::Error;

use longhorn_core::{LayoutContainerId, SurfaceId, SurfaceRequestId, SurfaceRevision, WindowId};
use longhorn_surfaces::{
    EmptyWindowPolicy, LayoutContainerCleanupIntent, ParticipatingWindow, SURFACE_PROTOCOL_VERSION,
    SurfaceChangedEvent, SurfaceDocument, SurfaceHostPreference, SurfaceMutationCommand,
    SurfaceMutationOutcome, SurfaceMutationReceipt, SurfaceMutationRejection,
    SurfaceMutationRejectionCode, SurfaceMutationRequest, SurfaceMutationResponse,
    SurfaceProtocolEpoch, SurfaceRecord, SurfaceSnapshot,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, string_union_variants, tagged_variants,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/surfaces/src/generated/protocol.ts";
const GOLDEN_FIXTURE: &str = "fixtures/surfaces/protocol-v1.json";

struct RenderedProtocol {
    contents: String,
    rejection_codes: Vec<String>,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render(&protocol.rejection_codes)?,
        },
    ];
    apply("Surface", "generate:surfaces", mode, &artifacts)
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let command_declaration = SurfaceMutationCommand::decl();
    let outcome_declaration = SurfaceMutationOutcome::decl();
    let rejection_declaration = SurfaceMutationRejectionCode::decl();
    let command_kinds = tagged_variants(&command_declaration, "kind")?;
    let outcome_kinds = tagged_variants(&outcome_declaration, "kind")?;
    let rejection_codes = string_union_variants(&rejection_declaration)?;
    let declarations = [
        LayoutContainerId::decl(),
        SurfaceId::decl(),
        SurfaceRequestId::decl(),
        WindowId::decl(),
        SurfaceRevision::decl(),
        SurfaceProtocolEpoch::decl(),
        SurfaceHostPreference::decl(),
        SurfaceRecord::decl(),
        ParticipatingWindow::decl(),
        SurfaceDocument::decl(),
        EmptyWindowPolicy::decl(),
        LayoutContainerCleanupIntent::decl(),
        command_declaration,
        SurfaceMutationRequest::decl(),
        outcome_declaration,
        SurfaceMutationReceipt::decl(),
        rejection_declaration,
        SurfaceMutationRejection::decl(),
        SurfaceMutationResponse::decl(),
        SurfaceSnapshot::decl(),
        SurfaceChangedEvent::decl(),
    ]
    .map(exported_declaration);
    let command_kinds_json = serde_json::to_string(&command_kinds)?;
    let outcome_kinds_json = serde_json::to_string(&outcome_kinds)?;
    let rejection_codes_json = serde_json::to_string(&rejection_codes)?;

    let contents = format!(
        "// @generated by `effigy generate:surfaces`; do not edit.\n\
         // Rust serde types are the wire authority.\n\n\
         export const SURFACE_PROTOCOL_VERSION = {SURFACE_PROTOCOL_VERSION} as const;\n\
         export const SURFACE_MUTATION_COMMAND_KINDS = {command_kinds_json} as const;\n\
         export const SURFACE_MUTATION_OUTCOME_KINDS = {outcome_kinds_json} as const;\n\
         export const SURFACE_MUTATION_REJECTION_CODES = {rejection_codes_json} as const;\n\n\
         {}\n",
        declarations.join("\n\n")
    );
    Ok(RenderedProtocol {
        contents,
        rejection_codes,
    })
}
