use std::error::Error;

use longhorn_core::{
    LayoutSchemaId, PanelDefinitionId, PanelInstanceId, RegionId, SizingSlotId, SurfaceId,
    SurfaceRequestId, SurfaceRevision, WindowId,
};
use longhorn_surfaces::{
    EmptyWindowPolicy, LayoutRatio, PanelInstance, ParticipatingWindow, RegionState,
    SURFACE_PROTOCOL_VERSION, SizingSlotState, SurfaceChangedEvent, SurfaceDocument,
    SurfaceHostPreference, SurfaceMutationCommand, SurfaceMutationOutcome, SurfaceMutationReceipt,
    SurfaceMutationRejection, SurfaceMutationRejectionCode, SurfaceMutationRequest,
    SurfaceMutationResponse, SurfacePresentation, SurfaceProtocolEpoch, SurfaceRecord,
    SurfaceSnapshot,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, field_map, string_union_variants,
    tagged_variants,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/surfaces/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/surfaces/generated/fields.ts";
const GOLDEN_FIXTURE: &str = "fixtures/surfaces/protocol-v1.json";
#[cfg(test)]
const LOOPHOLE_REGISTERED_AUTHORITY: &str =
    include_str!("../../../fixtures/surfaces/surface-bound-registered-authority-v1.json");

struct RenderedProtocol {
    contents: String,
    fields: String,
    rejection_codes: Vec<String>,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GENERATED_FIELDS,
            contents: protocol.fields,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render(&protocol.rejection_codes)?,
        },
    ];
    apply("Surface", "generate:surfaces", mode, &artifacts)
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let command_declaration = SurfaceMutationCommand::decl();
    let outcome_declaration = SurfaceMutationOutcome::decl();
    let rejection_declaration = SurfaceMutationRejectionCode::decl();
    let command_kinds = tagged_variants(&command_declaration, "kind")?;
    let outcome_kinds = tagged_variants(&outcome_declaration, "kind")?;
    let rejection_codes = string_union_variants(&rejection_declaration)?;
    let declarations = [
        LayoutSchemaId::decl(),
        RegionId::decl(),
        SizingSlotId::decl(),
        PanelInstanceId::decl(),
        SurfaceId::decl(),
        SurfaceRequestId::decl(),
        WindowId::decl(),
        SurfaceRevision::decl(),
        SurfaceProtocolEpoch::decl(),
        PanelDefinitionId::decl(),
        LayoutRatio::decl(),
        RegionState::decl(),
        SizingSlotState::decl(),
        PanelInstance::decl(),
        SurfaceHostPreference::decl(),
        SurfacePresentation::decl(),
        SurfaceRecord::decl(),
        ParticipatingWindow::decl(),
        SurfaceDocument::decl(),
        EmptyWindowPolicy::decl(),
        command_declaration,
        SurfaceMutationRequest::decl(),
        outcome_declaration,
        SurfaceMutationReceipt::decl(),
        rejection_declaration,
        SurfaceMutationRejection::decl(),
        SurfaceMutationResponse::decl(),
        SurfaceSnapshot::decl(),
        SurfaceChangedEvent::decl(),
    ]
    .map(exported_declaration);
    let command_kinds_json = serde_json::to_string(&command_kinds)?;
    let outcome_kinds_json = serde_json::to_string(&outcome_kinds)?;
    let rejection_codes_json = serde_json::to_string(&rejection_codes)?;

    let contents = format!(
        "// @generated by `effigy generate:surfaces`; do not edit.\n\
         // Rust serde types are the wire authority.\n\n\
         export const SURFACE_PROTOCOL_VERSION = {SURFACE_PROTOCOL_VERSION} as const;\n\
         export const SURFACE_MUTATION_COMMAND_KINDS = {command_kinds_json} as const;\n\
         export const SURFACE_MUTATION_OUTCOME_KINDS = {outcome_kinds_json} as const;\n\
         export const SURFACE_MUTATION_REJECTION_CODES = {rejection_codes_json} as const;\n\n\
         {}\n",
        declarations.join("\n\n")
    );
    let (fields, skipped) = field_map("generate:surfaces", "SURFACE_FIELDS", &declarations);
    if !skipped.is_empty() {
        // Tagged unions carry different fields per variant, so one flat list
        // would be wrong. Named rather than dropped silently.
        eprintln!(
            "[surfaces] tagged unions not in the field map: {}",
            skipped.join(", ")
        );
    }

    Ok(RenderedProtocol {
        contents,
        fields,
        rejection_codes,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn surface_bound_registered_surface_fixture_records_the_habitat_boundary() {
        let fixture: serde_json::Value =
            serde_json::from_str(LOOPHOLE_REGISTERED_AUTHORITY).unwrap();

        assert_eq!(fixture["domain"], "regional-surfaces");
        assert_eq!(fixture["regionalSurface"]["registered"], true);
        assert_eq!(fixture["focusedPanelSurface"]["registered"], false);
        assert_eq!(fixture["lifecycle"].as_array().unwrap().len(), 7);
        assert_eq!(
            fixture["composition"]["fullscreen"],
            "transient-native-only"
        );
    }
}
