use std::error::Error;

use longhorn_core::DisplayId;
use longhorn_surface_transfer::{
    SurfaceProvisioningCompletion, SurfaceSessionResponse, SurfaceSessionStartRequest,
    SurfaceTransferAbort, SurfaceTransferAbortSource, SurfaceTransferCommand,
    SurfaceTransferCompletion, SurfaceTransferErrorCode, SurfaceTransferResponse,
    SurfaceTransferTarget,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, field_map, string_union_variants,
    tagged_variants, variant_field_map,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/surface-transfer/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/surface-transfer/generated/fields.ts";
const GENERATED_VARIANT_FIELDS: &str =
    "packages/longhorn/src/surface-transfer/generated/variant-fields.ts";
const GOLDEN_FIXTURE: &str = "fixtures/surface-transfer/protocol-v1.json";

struct RenderedProtocol {
    contents: String,
    fields: String,
    error_codes: Vec<String>,
    variant_fields: String,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GENERATED_FIELDS,
            contents: protocol.fields,
        },
        Artifact {
            relative_path: GENERATED_VARIANT_FIELDS,
            contents: protocol.variant_fields,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render(&protocol.error_codes)?,
        },
    ];
    apply(
        "Surface transfer",
        "generate:surface-transfer",
        mode,
        &artifacts,
    )
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let target = SurfaceTransferTarget::decl();
    let abort_source = SurfaceTransferAbortSource::decl();
    let session_response = SurfaceSessionResponse::decl();
    let transfer_response = SurfaceTransferResponse::decl();
    let errors = SurfaceTransferErrorCode::decl();
    let target_kinds = tagged_variants(&target, "kind")?;
    let abort_domains = tagged_variants(&abort_source, "domain")?;
    let session_statuses = tagged_variants(&session_response, "status")?;
    let transfer_statuses = tagged_variants(&transfer_response, "status")?;
    let error_codes = string_union_variants(&errors)?;
    let declarations = [
        DisplayId::decl(),
        errors,
        SurfaceSessionStartRequest::decl(),
        SurfaceTransferCommand::decl(),
        SurfaceProvisioningCompletion::decl(),
        target,
        SurfaceTransferCompletion::decl(),
        abort_source,
        SurfaceTransferAbort::decl(),
        session_response,
        transfer_response,
    ]
    .map(exported_declaration);

    let contents = format!(
        "// @generated by `effigy generate:surface-transfer`; do not edit.\n\
         // Rust serde types are the wire authority.\n\n\
         import type {{ SurfaceDocument, SurfaceId, SurfaceMutationRejectionCode, SurfaceRevision }} from \"@inflatable-cookie/longhorn/surfaces\";\n\
         import type {{ DragSessionId, TransferCommitSelector, TransferCommittedTarget, TransferErrorCode, TransferHostBindingId, TransferProtocolVersion, TransferRequestId, TransferSessionStarted, WindowId }} from \"@inflatable-cookie/longhorn/transfer\";\n\n\
         export const SURFACE_TRANSFER_TARGET_KINDS = {} as const;\n\
         export const SURFACE_TRANSFER_ABORT_DOMAINS = {} as const;\n\
         export const SURFACE_SESSION_RESPONSE_STATUSES = {} as const;\n\
         export const SURFACE_TRANSFER_RESPONSE_STATUSES = {} as const;\n\
         export const SURFACE_TRANSFER_ERROR_CODES = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&target_kinds)?,
        serde_json::to_string(&abort_domains)?,
        serde_json::to_string(&session_statuses)?,
        serde_json::to_string(&transfer_statuses)?,
        serde_json::to_string(&error_codes)?,
        declarations.join("\n\n")
    );
    let (fields, skipped) = field_map(
        "generate:surface-transfer",
        "SURFACE_TRANSFER_FIELDS",
        &declarations,
    );
    if !skipped.is_empty() {
        eprintln!(
            "[surface-transfer] tagged unions not in the field map: {}",
            skipped.join(", ")
        );
    }

    let (variant_fields, unreadable) = variant_field_map(
        "generate:surface-transfer",
        "SURFACE_TRANSFER_VARIANT_FIELDS",
        &declarations,
    );

    if !unreadable.is_empty() {
        eprintln!(
            "[surface-transfer] unreadable unions: {}",
            unreadable.join(", ")
        );
    }

    Ok(RenderedProtocol {
        variant_fields,
        contents,
        fields,
        error_codes,
    })
}
