use std::error::Error;

use longhorn_core::{
    LayoutSchemaId, PanelDefinitionId, PanelInstanceId, RegionId, SizingSlotId, SurfaceId,
    SurfaceRequestId, SurfaceRevision, WindowId,
};
use longhorn_surfaces::{
    EmptyWindowPolicy, LayoutRatio, PanelInstance, ParticipatingWindow, RegionState,
    SURFACE_PROTOCOL_VERSION, SizingSlotState, SurfaceChangedEvent, SurfaceDocument,
    SurfaceHostPreference, SurfaceMutationCommand, SurfaceMutationOutcome, SurfaceMutationReceipt,
    SurfaceMutationRejection, SurfaceMutationRejectionCode, SurfaceMutationRequest,
    SurfaceMutationResponse, SurfacePresentation, SurfaceProtocolEpoch, SurfaceRecord,
    SurfaceSnapshot,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, config, exported_declaration, field_map,
    string_union_variants, tagged_variants, variant_field_map,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/surfaces/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/surfaces/generated/fields.ts";
const GENERATED_VARIANT_FIELDS: &str = "packages/longhorn/src/surfaces/generated/variant-fields.ts";
const GOLDEN_FIXTURE: &str = "fixtures/surfaces/protocol-v1.json";
#[cfg(test)]
const LOOPHOLE_REGISTERED_AUTHORITY: &str =
    include_str!("../../../fixtures/surfaces/surface-bound-registered-authority-v1.json");

struct RenderedProtocol {
    contents: String,
    fields: String,
    rejection_codes: Vec<String>,
    variant_fields: String,
}

/// Generates or checks the surface bindings and golden fixtures.
pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GENERATED_FIELDS,
            contents: protocol.fields,
        },
        Artifact {
            relative_path: GENERATED_VARIANT_FIELDS,
            contents: protocol.variant_fields,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render(&protocol.rejection_codes)?,
        },
    ];
    apply("Surface", "generate:surfaces", mode, &artifacts)
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let command_declaration = SurfaceMutationCommand::decl(config());
    let outcome_declaration = SurfaceMutationOutcome::decl(config());
    let rejection_declaration = SurfaceMutationRejectionCode::decl(config());
    let command_kinds = tagged_variants(&command_declaration, "kind")?;
    let outcome_kinds = tagged_variants(&outcome_declaration, "kind")?;
    let rejection_codes = string_union_variants(&rejection_declaration)?;
    let declarations = [
        LayoutSchemaId::decl(config()),
        RegionId::decl(config()),
        SizingSlotId::decl(config()),
        PanelInstanceId::decl(config()),
        SurfaceId::decl(config()),
        SurfaceRequestId::decl(config()),
        WindowId::decl(config()),
        SurfaceRevision::decl(config()),
        SurfaceProtocolEpoch::decl(config()),
        PanelDefinitionId::decl(config()),
        LayoutRatio::decl(config()),
        RegionState::decl(config()),
        SizingSlotState::decl(config()),
        PanelInstance::decl(config()),
        SurfaceHostPreference::decl(config()),
        SurfacePresentation::decl(config()),
        SurfaceRecord::decl(config()),
        ParticipatingWindow::decl(config()),
        SurfaceDocument::decl(config()),
        EmptyWindowPolicy::decl(config()),
        command_declaration,
        SurfaceMutationRequest::decl(config()),
        outcome_declaration,
        SurfaceMutationReceipt::decl(config()),
        rejection_declaration,
        SurfaceMutationRejection::decl(config()),
        SurfaceMutationResponse::decl(config()),
        SurfaceSnapshot::decl(config()),
        SurfaceChangedEvent::decl(config()),
    ]
    .map(exported_declaration);
    let command_kinds_json = serde_json::to_string(&command_kinds)?;
    let outcome_kinds_json = serde_json::to_string(&outcome_kinds)?;
    let rejection_codes_json = serde_json::to_string(&rejection_codes)?;

    let contents = format!(
        "// @generated by `effigy generate:surfaces`; do not edit.\n\
         // Rust serde types are the wire authority.\n\n\
         export const SURFACE_PROTOCOL_VERSION = {SURFACE_PROTOCOL_VERSION} as const;\n\
         export const SURFACE_MUTATION_COMMAND_KINDS = {command_kinds_json} as const;\n\
         export const SURFACE_MUTATION_OUTCOME_KINDS = {outcome_kinds_json} as const;\n\
         export const SURFACE_MUTATION_REJECTION_CODES = {rejection_codes_json} as const;\n\n\
         {}\n",
        declarations.join("\n\n")
    );
    let (fields, _skipped) = field_map("generate:surfaces", "SURFACE_FIELDS", &declarations);
    let variant_fields =
        variant_field_map("generate:surfaces", "SURFACE_VARIANT_FIELDS", &declarations);

    Ok(RenderedProtocol {
        variant_fields,
        contents,
        fields,
        rejection_codes,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn surface_bound_registered_surface_fixture_records_the_habitat_boundary() {
        let fixture: serde_json::Value =
            serde_json::from_str(LOOPHOLE_REGISTERED_AUTHORITY).unwrap();

        assert_eq!(fixture["domain"], "regional-surfaces");
        assert_eq!(fixture["regionalSurface"]["registered"], true);
        assert_eq!(fixture["focusedPanelSurface"]["registered"], false);
        assert_eq!(fixture["lifecycle"].as_array().unwrap().len(), 7);
        assert_eq!(
            fixture["composition"]["fullscreen"],
            "transient-native-only"
        );
    }
}
