use std::error::Error;

use longhorn_core::{
    ClientLogicalPx, ClientPoint, ClientRect, ClientSize, DomainId, DropZoneId, TransferClientId,
    TransferHostBindingId, TransferRequestId, WindowId,
};
use longhorn_transfer::{
    ClientDropZone, ClientEpoch, DragSessionId, InsertionPosition, LeaseGeneration,
    PanelHostBindingKind, PanelSessionStartRequest, PanelTransferCommand, PanelTransferCompletion,
    PanelTransferErrorCode, PanelTransferResponse, SessionCancellationStatus,
    TRANSFER_PROTOCOL_VERSION, TargetResolutionPath, TransferAbort, TransferAbortSource,
    TransferCancelReceipt, TransferCancelRequest, TransferCancelResponse, TransferCapability,
    TransferClientSnapshot, TransferCommitSelector, TransferCommittedTarget, TransferErrorCode,
    TransferLeaseReceipt, TransferLeaseRequest, TransferLeaseResponse, TransferPayload,
    TransferProtocolVersion, TransferRevision, TransferSessionResponse, TransferSessionStarted,
    TransferTargetBinding,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, field_map, string_union_variants,
    tagged_variants,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/transfer/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/transfer/generated/fields.ts";
const GOLDEN_FIXTURE: &str = "fixtures/transfer/protocol-v1.json";

struct RenderedProtocol {
    contents: String,
    fields: String,
    transfer_error_codes: Vec<String>,
    panel_error_codes: Vec<String>,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    let artifacts = [
        Artifact {
            relative_path: GENERATED_PROTOCOL,
            contents: protocol.contents,
        },
        Artifact {
            relative_path: GENERATED_FIELDS,
            contents: protocol.fields,
        },
        Artifact {
            relative_path: GOLDEN_FIXTURE,
            contents: fixture::render(&protocol.transfer_error_codes, &protocol.panel_error_codes)?,
        },
    ];
    apply("transfer", "generate:transfer", mode, &artifacts)
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let target_binding = TransferTargetBinding::decl();
    let commit_selector = TransferCommitSelector::decl();
    let abort_source = TransferAbortSource::decl();
    let session_response = TransferSessionResponse::decl();
    let lease_response = TransferLeaseResponse::decl();
    let cancel_response = TransferCancelResponse::decl();
    let panel_response = PanelTransferResponse::decl();
    let transfer_errors = TransferErrorCode::decl();
    let panel_errors = PanelTransferErrorCode::decl();

    let target_kinds = tagged_variants(&target_binding, "kind")?;
    let selector_kinds = tagged_variants(&commit_selector, "kind")?;
    let abort_domains = tagged_variants(&abort_source, "domain")?;
    let session_statuses = tagged_variants(&session_response, "status")?;
    let lease_statuses = tagged_variants(&lease_response, "status")?;
    let cancel_statuses = tagged_variants(&cancel_response, "status")?;
    let panel_statuses = tagged_variants(&panel_response, "status")?;
    let transfer_error_codes = string_union_variants(&transfer_errors)?;
    let panel_error_codes = string_union_variants(&panel_errors)?;

    let declarations = [
        DomainId::decl(),
        DropZoneId::decl(),
        TransferClientId::decl(),
        TransferHostBindingId::decl(),
        TransferRequestId::decl(),
        WindowId::decl(),
        ClientLogicalPx::decl(),
        ClientPoint::decl(),
        ClientSize::decl(),
        ClientRect::decl(),
        DragSessionId::decl(),
        ClientEpoch::decl(),
        LeaseGeneration::decl(),
        TransferRevision::decl(),
        InsertionPosition::decl(),
        TransferProtocolVersion::decl(),
        TransferCapability::decl(),
        target_binding,
        TransferPayload::decl(),
        SessionCancellationStatus::decl(),
        TargetResolutionPath::decl(),
        PanelHostBindingKind::decl(),
        transfer_errors,
        panel_errors,
        PanelSessionStartRequest::decl(),
        TransferCancelRequest::decl(),
        ClientDropZone::decl(),
        TransferLeaseRequest::decl(),
        commit_selector,
        PanelTransferCommand::decl(),
        TransferClientSnapshot::decl(),
        TransferSessionStarted::decl(),
        TransferLeaseReceipt::decl(),
        TransferCancelReceipt::decl(),
        TransferCommittedTarget::decl(),
        PanelTransferCompletion::decl(),
        abort_source,
        TransferAbort::decl(),
        session_response,
        lease_response,
        cancel_response,
        panel_response,
    ]
    .map(exported_declaration);

    let contents = format!(
        "// @generated by `effigy generate:transfer`; do not edit.\n\
         // Rust serde types are the wire authority.\n\n\
         import type {{ LayoutContainerId, LayoutDocument, LayoutRevision, PanelInstanceId, RegionId }} from \"@inflatable-cookie/longhorn/layout\";\n\n\
         export const TRANSFER_PROTOCOL_VERSION = {TRANSFER_PROTOCOL_VERSION} as const;\n\
         export const TRANSFER_TARGET_BINDING_KINDS = {} as const;\n\
         export const TRANSFER_COMMIT_SELECTOR_KINDS = {} as const;\n\
         export const TRANSFER_ABORT_DOMAINS = {} as const;\n\
         export const TRANSFER_SESSION_RESPONSE_STATUSES = {} as const;\n\
         export const TRANSFER_LEASE_RESPONSE_STATUSES = {} as const;\n\
         export const TRANSFER_CANCEL_RESPONSE_STATUSES = {} as const;\n\
         export const PANEL_TRANSFER_RESPONSE_STATUSES = {} as const;\n\
         export const TRANSFER_ERROR_CODES = {} as const;\n\
         export const PANEL_TRANSFER_ERROR_CODES = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&target_kinds)?,
        serde_json::to_string(&selector_kinds)?,
        serde_json::to_string(&abort_domains)?,
        serde_json::to_string(&session_statuses)?,
        serde_json::to_string(&lease_statuses)?,
        serde_json::to_string(&cancel_statuses)?,
        serde_json::to_string(&panel_statuses)?,
        serde_json::to_string(&transfer_error_codes)?,
        serde_json::to_string(&panel_error_codes)?,
        declarations.join("\n\n")
    );
    let (fields, skipped) = field_map("generate:transfer", "TRANSFER_FIELDS", &declarations);
    if !skipped.is_empty() {
        eprintln!(
            "[transfer] tagged unions not in the field map: {}",
            skipped.join(", ")
        );
    }

    Ok(RenderedProtocol {
        contents,
        fields,
        transfer_error_codes,
        panel_error_codes,
    })
}
