use std::error::Error;

use longhorn_update::{
    Channel, DeferralCause, InstallManager, OfferReason, UPDATE_PROTOCOL_VERSION,
    UpdateAvailabilityProjection, UpdateChangedEvent, UpdateChangedKind, UpdateCheckCommand,
    UpdateDeferCommand, UpdateDeferralProjection, UpdateInstallAuthorizationProjection,
    UpdateInstallCommand, UpdateProgressProjection, UpdateProtocolVersion,
    UpdateSelectChannelCommand, UpdateSnapshot,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, exported_declaration, field_map, string_union_variants,
    tagged_variants, variant_field_map,
};

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/update/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/update/generated/fields.ts";
const GENERATED_VARIANT_FIELDS: &str = "packages/longhorn/src/update/generated/variant-fields.ts";

struct RenderedProtocol {
    contents: String,
    fields: String,
    variant_fields: String,
}

pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    apply(
        "update",
        "generate:update",
        mode,
        &[
            Artifact {
                relative_path: GENERATED_PROTOCOL,
                contents: protocol.contents,
            },
            Artifact {
                relative_path: GENERATED_FIELDS,
                contents: protocol.fields,
            },
            Artifact {
                relative_path: GENERATED_VARIANT_FIELDS,
                contents: protocol.variant_fields,
            },
        ],
    )
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let channel = Channel::decl();
    let offer_reason = OfferReason::decl();
    let install_manager = InstallManager::decl();
    let deferral_cause = DeferralCause::decl();
    let availability = UpdateAvailabilityProjection::decl();
    let progress = UpdateProgressProjection::decl();
    let authorization = UpdateInstallAuthorizationProjection::decl();
    let changed_kind = UpdateChangedKind::decl();

    let declarations = [
        UpdateProtocolVersion::decl(),
        channel.clone(),
        offer_reason.clone(),
        install_manager.clone(),
        deferral_cause.clone(),
        availability.clone(),
        UpdateDeferralProjection::decl(),
        progress.clone(),
        UpdateSnapshot::decl(),
        UpdateCheckCommand::decl(),
        UpdateSelectChannelCommand::decl(),
        UpdateDeferCommand::decl(),
        UpdateInstallCommand::decl(),
        authorization.clone(),
        changed_kind.clone(),
        UpdateChangedEvent::decl(),
    ]
    .map(exported_declaration);

    let contents = format!(
        "// @generated by `effigy generate:update`; do not edit.\n\
         // Rust serde types are the wire authority. Versions are strings, as\n\
         // `semver::Version` serialises them.\n\n\
         export const UPDATE_PROTOCOL_VERSION = {UPDATE_PROTOCOL_VERSION} as const;\n\
         export const UPDATE_CHANNELS = {} as const;\n\
         export const UPDATE_OFFER_REASONS = {} as const;\n\
         export const UPDATE_INSTALL_MANAGERS = {} as const;\n\
         export const UPDATE_DEFERRAL_CAUSES = {} as const;\n\
         export const UPDATE_AVAILABILITY_STATES = {} as const;\n\
         export const UPDATE_PROGRESS_STATES = {} as const;\n\
         export const UPDATE_INSTALL_AUTHORIZATION_STATUSES = {} as const;\n\
         export const UPDATE_CHANGED_KINDS = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&string_union_variants(&channel)?)?,
        serde_json::to_string(&string_union_variants(&offer_reason)?)?,
        serde_json::to_string(&string_union_variants(&install_manager)?)?,
        serde_json::to_string(&tagged_variants(&deferral_cause, "cause")?)?,
        serde_json::to_string(&tagged_variants(&availability, "state")?)?,
        serde_json::to_string(&tagged_variants(&progress, "state")?)?,
        serde_json::to_string(&tagged_variants(&authorization, "status")?)?,
        serde_json::to_string(&string_union_variants(&changed_kind)?)?,
        declarations.join("\n\n"),
    );

    let (fields, _skipped) = field_map("generate:update", "UPDATE_FIELDS", &declarations);
    let variant_fields =
        variant_field_map("generate:update", "UPDATE_VARIANT_FIELDS", &declarations);

    Ok(RenderedProtocol {
        contents,
        fields,
        variant_fields,
    })
}
