use std::error::Error;

use longhorn_update::{
    Channel, DeferralCause, InstallManager, OfferReason, UPDATE_PROTOCOL_VERSION,
    UpdateAvailabilityProjection, UpdateChangedEvent, UpdateChangedKind, UpdateCheckCommand,
    UpdateDeferCommand, UpdateDeferralProjection, UpdateInstallAuthorizationProjection,
    UpdateInstallCommand, UpdateOutcomeProjection, UpdateProgressProjection, UpdateProtocolVersion,
    UpdateRejectionCode, UpdateSelectChannelCommand, UpdateSnapshot,
};
use ts_rs::TS;

use crate::generation::{
    Artifact, GenerationMode, apply, config, exported_declaration, field_map,
    string_union_variants, tagged_variants, variant_field_map,
};

mod fixture;

const GENERATED_PROTOCOL: &str = "packages/longhorn/src/update/generated/protocol.ts";
const GENERATED_FIELDS: &str = "packages/longhorn/src/update/generated/fields.ts";
const GENERATED_VARIANT_FIELDS: &str = "packages/longhorn/src/update/generated/variant-fields.ts";
const GOLDEN_FIXTURE: &str = "fixtures/update/protocol-v1.json";

struct RenderedProtocol {
    contents: String,
    fields: String,
    variant_fields: String,
}

/// Generates or checks the update bindings and golden fixtures.
pub fn run(mode: GenerationMode) -> Result<(), Box<dyn Error>> {
    let protocol = render_protocol()?;
    apply(
        "update",
        "generate:update",
        mode,
        &[
            Artifact {
                relative_path: GENERATED_PROTOCOL,
                contents: protocol.contents,
            },
            Artifact {
                relative_path: GENERATED_FIELDS,
                contents: protocol.fields,
            },
            Artifact {
                relative_path: GENERATED_VARIANT_FIELDS,
                contents: protocol.variant_fields,
            },
            Artifact {
                relative_path: GOLDEN_FIXTURE,
                contents: fixture::render()?,
            },
        ],
    )
}

fn render_protocol() -> Result<RenderedProtocol, Box<dyn Error>> {
    let channel = Channel::decl(config());
    let offer_reason = OfferReason::decl(config());
    let install_manager = InstallManager::decl(config());
    let deferral_cause = DeferralCause::decl(config());
    let availability = UpdateAvailabilityProjection::decl(config());
    let progress = UpdateProgressProjection::decl(config());
    let authorization = UpdateInstallAuthorizationProjection::decl(config());
    let rejection_code = UpdateRejectionCode::decl(config());
    let outcome = UpdateOutcomeProjection::decl(config());
    let changed_kind = UpdateChangedKind::decl(config());

    let declarations = [
        UpdateProtocolVersion::decl(config()),
        channel.clone(),
        offer_reason.clone(),
        install_manager.clone(),
        deferral_cause.clone(),
        availability.clone(),
        UpdateDeferralProjection::decl(config()),
        progress.clone(),
        UpdateSnapshot::decl(config()),
        UpdateCheckCommand::decl(config()),
        UpdateSelectChannelCommand::decl(config()),
        UpdateDeferCommand::decl(config()),
        UpdateInstallCommand::decl(config()),
        authorization.clone(),
        rejection_code.clone(),
        outcome.clone(),
        changed_kind.clone(),
        UpdateChangedEvent::decl(config()),
    ]
    .map(exported_declaration);

    let contents = format!(
        "// @generated by `effigy generate:update`; do not edit.\n\
         // Rust serde types are the wire authority. Versions are strings, as\n\
         // `semver::Version` serialises them.\n\n\
         export const UPDATE_PROTOCOL_VERSION = {UPDATE_PROTOCOL_VERSION} as const;\n\
         export const UPDATE_CHANNELS = {} as const;\n\
         export const UPDATE_OFFER_REASONS = {} as const;\n\
         export const UPDATE_INSTALL_MANAGERS = {} as const;\n\
         export const UPDATE_DEFERRAL_CAUSES = {} as const;\n\
         export const UPDATE_AVAILABILITY_STATES = {} as const;\n\
         export const UPDATE_PROGRESS_STATES = {} as const;\n\
         export const UPDATE_INSTALL_AUTHORIZATION_STATUSES = {} as const;\n\
         export const UPDATE_REJECTION_CODES = {} as const;\n\
         export const UPDATE_OUTCOME_STATUSES = {} as const;\n\
         export const UPDATE_CHANGED_KINDS = {} as const;\n\n\
         {}\n",
        serde_json::to_string(&string_union_variants(&channel)?)?,
        serde_json::to_string(&string_union_variants(&offer_reason)?)?,
        serde_json::to_string(&string_union_variants(&install_manager)?)?,
        serde_json::to_string(&tagged_variants(&deferral_cause, "cause")?)?,
        serde_json::to_string(&tagged_variants(&availability, "state")?)?,
        serde_json::to_string(&tagged_variants(&progress, "state")?)?,
        serde_json::to_string(&tagged_variants(&authorization, "status")?)?,
        serde_json::to_string(&string_union_variants(&rejection_code)?)?,
        serde_json::to_string(&tagged_variants(&outcome, "status")?)?,
        serde_json::to_string(&string_union_variants(&changed_kind)?)?,
        declarations.join("\n\n"),
    );

    let (fields, _skipped) = field_map("generate:update", "UPDATE_FIELDS", &declarations);
    let variant_fields =
        variant_field_map("generate:update", "UPDATE_VARIANT_FIELDS", &declarations);

    Ok(RenderedProtocol {
        contents,
        fields,
        variant_fields,
    })
}
