[package]
name = "longhorn-native-content-soundcheck-artifact-proof"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
longhorn-native-content-artifact-proof-common.workspace = true
longhorn-native-content-isolated-window.workspace = true
