[package]
name = "longhorn-native-content-isolated-window-prototype"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
longhorn-core.workspace = true
longhorn-native-content-prototype.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
