import { createHash } from "node:crypto";
import { access, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";

type CargoMetadata = {
  packages: Array<{
    name: string;
    version: string;
    manifest_path: string;
    features: Record<string, string[]>;
    publish: string[] | null;
    targets: Array<{ kind: string[]; src_path: string }>;
  }>;
};

type PackageManifest = {
  name: string;
  version: string;
  private?: boolean;
  license?: string;
  publishConfig?: { access?: string };
  repository?: { directory?: string };
  exports: Record<string, string | Record<string, string>>;
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
  peerDependenciesMeta?: Record<string, { optional?: boolean }>;
};

const repoRoot = resolve(import.meta.dir, "..");
const outputPath = join(repoRoot, "docs/reference/api-surface.md");
const write = process.argv.includes("--write");

const content = await renderReference();
if (write) {
  await writeFile(outputPath, content);
} else {
  const current = await readFile(outputPath, "utf8");
  if (current !== content) {
    throw new Error("API surface reference is stale; run `effigy generate:api-reference-card126`");
  }
}

console.log(JSON.stringify({
  schema: "longhorn.api-reference-generation.v1",
  mode: write ? "write" : "check",
  output: relative(repoRoot, outputPath),
  sha256: createHash("sha256").update(content).digest("hex"),
}, null, 2));

async function renderReference(): Promise<string> {
  const cargo = JSON.parse(await run(["cargo", "metadata", "--locked", "--no-deps", "--format-version", "1"])) as CargoMetadata;
  const crateRoot = join(repoRoot, "crates") + sep;
  const rustPackages = cargo.packages
    .filter(({ manifest_path, name }) => manifest_path.startsWith(crateRoot) && name.startsWith("longhorn-"))
    .sort((left, right) => left.name.localeCompare(right.name));
  const crateDirectories = (await readdir(join(repoRoot, "crates"), { withFileTypes: true }))
    .filter((entry) => entry.isDirectory());
  if (rustPackages.length !== crateDirectories.length) {
    throw new Error(`Rust inventory mismatch: metadata ${rustPackages.length}, directories ${crateDirectories.length}`);
  }

  const packageDirectories = (await readdir(join(repoRoot, "packages"), { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name));
  const typescriptPackages = [];
  for (const directory of packageDirectories) {
    const manifestPath = join(repoRoot, "packages", directory.name, "package.json");
    if (!(await exists(manifestPath))) continue;
    const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as PackageManifest;
    if (manifest.name !== "@inflatable-cookie/longhorn" && !manifest.name.startsWith("@inflatable-cookie/longhorn-") || manifest.version !== "0.1.0") {
      throw new Error(`${directory.name} package identity drift`);
    }
    // These carried `private: true` until Card 166 made them publishable. The
    // posture to hold is now the publishable one: a scoped package needs
    // `publishConfig.access` to go out publicly, and a tarball without a
    // licence is worse than one that never ships.
    if (manifest.private === true || manifest.publishConfig?.access !== "public" || manifest.license !== "MIT" || manifest.repository?.directory !== `packages/${directory.name}`) {
      throw new Error(`${directory.name} publish posture drift`);
    }
    const entrypoints = [];
    for (const [subpath, target] of Object.entries(manifest.exports)) {
      if (subpath === "./package.json") continue;
      const source = typeof target === "string"
        ? target
        : target.types ?? target.svelte ?? target.import ?? target.default;
      if (!source?.startsWith("./src/") || source.includes("../")) {
        throw new Error(`${manifest.name} export ${subpath} escapes public source roots`);
      }
      await access(join(dirname(manifestPath), source));
      entrypoints.push(subpath === "." ? manifest.name : `${manifest.name}/${subpath.slice(2)}`);
    }
    typescriptPackages.push({ directory: directory.name, manifest, entrypoints: entrypoints.sort() });
  }

  const lines = [
    "# Generated API Surface",
    "",
    "> Generated by `scripts/generate-api-reference-card126.ts`. Do not edit by hand.",
    "> The three TypeScript packages are prepared for npm publication at `0.1.0` under MIT; the Rust crates set `publish = false` and are not on crates.io.",
    "",
    "## Rust Crates",
    "",
    "`cargo doc` is the symbol-level reference. This table is the checked package and feature front door.",
    "",
    "| Crate | Kind | Features | Source reference |",
    "| --- | --- | --- | --- |",
  ];

  for (const pkg of rustPackages) {
    if (pkg.version !== "0.1.0" || pkg.publish === null || pkg.publish.length !== 0) {
      throw new Error(`${pkg.name} version or private publication posture drift`);
    }
    const directory = dirname(pkg.manifest_path);
    const relativeDirectory = relative(repoRoot, directory).split(sep).join("/");
    const readme = join(directory, "README.md");
    const library = pkg.targets.find(({ kind }) => kind.includes("lib"));
    const reference = await exists(readme)
      ? `../../${relativeDirectory}/README.md`
      : library
        ? `../../${relative(repoRoot, library.src_path).split(sep).join("/")}`
        : `../../${relativeDirectory}/Cargo.toml`;
    const kind = library ? "library" : "development tool";
    const features = formatFeatures(pkg.features);
    lines.push(`| \`${pkg.name}\` | ${kind} | ${features} | [source](${reference}) |`);
  }

  lines.push(
    "",
    "All crates currently set `publish = false`. `longhorn-bindings` is a development tool, not a consumer dependency.",
    "",
    "## TypeScript And Svelte Packages",
    "",
    "Entrypoints come only from each package's checked `exports` map. A subpath is optional only when its peer is selected explicitly.",
    "",
    "| Package | Public entrypoints | Longhorn dependencies | Peer ranges | Reference |",
    "| --- | --- | --- | --- | --- |",
  );

  for (const { directory, manifest, entrypoints } of typescriptPackages) {
    const dependencies = Object.entries(manifest.dependencies ?? {})
      .filter(([name]) => name === "@inflatable-cookie/longhorn" || name.startsWith("@inflatable-cookie/longhorn-"))
      .map(([name, version]) => `\`${name} ${version}\``);
    const peers = Object.entries(manifest.peerDependencies ?? {}).map(([name, version]) => {
      const optional = manifest.peerDependenciesMeta?.[name]?.optional === true ? "; optional" : "";
      return `\`${name} ${version}${optional}\``;
    });
    lines.push(
      `| \`${manifest.name}\` | ${entrypoints.map((entry) => `\`${entry}\``).join("<br>")} | ${dependencies.join("<br>") || "none"} | ${peers.join("<br>") || "none"} | [README](../../packages/${directory}/README.md) |`,
    );
  }

  lines.push(
    "",
    "Each package carries `publishConfig.access: public`, an MIT licence, and a repository directory, so `npm publish` is possible. Publication itself is Card 166's, and a guide may only imply registry installation once that has happened.",
  );
  return `${lines.join("\n")}\n`;
}

function formatFeatures(features: Record<string, string[]>): string {
  const names = Object.keys(features).sort();
  if (names.length === 0) return "none";
  return names.map((name) => `\`${name}\``).join(", ");
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function run(command: string[]): Promise<string> {
  const process = Bun.spawn(command, { cwd: repoRoot, stdout: "pipe", stderr: "pipe" });
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(process.stdout).text(),
    new Response(process.stderr).text(),
    process.exited,
  ]);
  if (exitCode !== 0) throw new Error(`${command.join(" ")} failed\n${stdout}\n${stderr}`);
  return stdout;
}
