import { describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  compareSemver,
  parseSemver,
  parseWorkspacePackageVersion,
} from "./longhorn-version.ts";
import {
  bumpPackageManifest,
  bumpRelease,
  bumpSkillStamp,
  promoteChangelog,
  replaceLonghornPathPins,
  replaceWorkspacePackageVersion,
} from "./release-bump.ts";
import { assessLock, parseLock, rewriteLonghornPathVersions } from "./sync-prototype-locks.ts";

const cargo = `[workspace.package]
version = "0.2.1"
edition = "2024"

[workspace.dependencies]
age = { version = "=0.12.1", default-features = false }
longhorn-core = { path = "crates/longhorn-core", version = "0.2.1" }
longhorn-bridge = { path = "crates/longhorn-bridge", version = "0.2.1" }
`;

describe("longhorn version source", () => {
  test("reads workspace.package.version", () => {
    expect(parseWorkspacePackageVersion(cargo)).toBe("0.2.1");
  });

  test("compares semver numerically", () => {
    expect(compareSemver("0.2.10", "0.2.9")).toBe(1);
    expect(compareSemver("0.2.1", "0.2.1")).toBe(0);
    expect(compareSemver("0.2.0", "0.2.1")).toBe(-1);
    expect(() => parseSemver("0.2")).toThrow(/X\.Y\.Z/);
  });
});

describe("release bump transforms", () => {
  test("replaces workspace version and Longhorn path pins only", () => {
    const next = replaceLonghornPathPins(replaceWorkspacePackageVersion(cargo, "0.2.2"), "0.2.2");
    expect(next).toContain('version = "0.2.2"');
    expect(next).toContain('age = { version = "=0.12.1"');
    expect(next).toContain('longhorn-core = { path = "crates/longhorn-core", version = "0.2.2" }');
    expect(next).toContain('longhorn-bridge = { path = "crates/longhorn-bridge", version = "0.2.2" }');
  });

  test("bumps package version and Longhorn peer", () => {
    const manifest = `{
  "name": "@inflatable-cookie/longhorn-tauri",
  "version": "0.2.1",
  "peerDependencies": {
    "@inflatable-cookie/longhorn": "0.2.1",
    "@tauri-apps/api": "^2.10.1"
  }
}
`;
    expect(bumpPackageManifest(manifest, "0.2.2")).toContain('"version": "0.2.2"');
    expect(bumpPackageManifest(manifest, "0.2.2")).toContain('"@inflatable-cookie/longhorn": "0.2.2"');
    expect(bumpPackageManifest(manifest, "0.2.2")).toContain('"@tauri-apps/api": "^2.10.1"');
  });

  test("promotes empty Unreleased and is idempotent", () => {
    const changelog = `# Changelog\n\n## [Unreleased]\n\n## [0.2.1] - 2026-09-25\n`;
    const once = promoteChangelog(changelog, "0.2.2", "2026-09-26");
    expect(once).toBe(
      `# Changelog\n\n## [Unreleased]\n\n## [0.2.2] - 2026-09-26\n\n## [0.2.1] - 2026-09-25\n`,
    );
    expect(promoteChangelog(once, "0.2.2", "2026-09-27")).toBe(once);
  });

  test("moves Unreleased notes under the new heading", () => {
    const changelog = `## [Unreleased]\n\n### Added\n- thing\n\n## [0.2.1] - 2026-09-25\n`;
    expect(promoteChangelog(changelog, "0.2.2", "2026-09-26")).toBe(
      `## [Unreleased]\n\n## [0.2.2] - 2026-09-26\n\n### Added\n- thing\n\n## [0.2.1] - 2026-09-25\n`,
    );
  });

  test("rewrites the skill stamp", () => {
    expect(bumpSkillStamp('---\nlonghorn_version: "0.2.1"\n---\n', "0.2.2")).toBe(
      '---\nlonghorn_version: "0.2.2"\n---\n',
    );
  });
});

const lock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "longhorn-core"
version = "0.2.1"

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

describe("lock safety", () => {
  test("rewrites only Longhorn path versions", () => {
    const next = rewriteLonghornPathVersions(lock, "0.2.2");
    const assessment = assessLock(parseLock(lock), parseLock(next), "0.2.2");
    expect(assessment.bumped).toEqual(["longhorn-core 0.2.1 -> 0.2.2"]);
    expect(assessment.thirdPartyMoved).toEqual([]);
    expect(assessment.unexpected).toEqual([]);
    expect(next).toContain('name = "serde"\nversion = "1.0.0"');
  });

  test("fails when a third-party lock line moves", () => {
    const moved = lock.replace('name = "serde"\nversion = "1.0.0"', 'name = "serde"\nversion = "1.0.1"');
    const assessment = assessLock(parseLock(lock), parseLock(moved), "0.2.2");
    expect(assessment.thirdPartyMoved.length).toBeGreaterThan(0);
  });
});

describe("release:bump", () => {
  test("refuses a non-increasing version and is idempotent at the same version", async () => {
    const root = await fixtureRepo("0.2.1");
    await expect(bumpRelease({
      repoRoot: root,
      version: "0.2.0",
      syncLocks: async () => undefined,
      regenerateApiReference: async () => undefined,
    })).rejects.toThrow(/non-increasing/);

    const first = await bumpRelease({
      repoRoot: root,
      version: "0.2.2",
      date: "2026-09-26",
      syncLocks: async () => undefined,
      regenerateApiReference: async (repoRoot) => {
        await writeFile(join(repoRoot, "docs/reference/api-surface.md"), "generated 0.2.2\n");
      },
    });
    expect(first.idempotent).toBe(false);
    expect(await readFile(join(root, "Cargo.toml"), "utf8")).toContain('version = "0.2.2"');
    expect(await readFile(join(root, "packages/longhorn-tauri/package.json"), "utf8")).toContain(
      '"@inflatable-cookie/longhorn": "0.2.2"',
    );
    expect(await readFile(join(root, "CHANGELOG.md"), "utf8")).toContain("## [0.2.2] - 2026-09-26");
    expect(await readFile(join(root, "skills/agent-control/SKILL.md"), "utf8")).toContain(
      'longhorn_version: "0.2.2"',
    );

    const second = await bumpRelease({
      repoRoot: root,
      version: "0.2.2",
      date: "2026-09-27",
      syncLocks: async () => undefined,
      regenerateApiReference: async () => undefined,
    });
    expect(second.idempotent).toBe(true);
    expect(second.changed).toEqual([]);
    expect(await readFile(join(root, "CHANGELOG.md"), "utf8")).toContain("## [0.2.2] - 2026-09-26");
  });

  test("fails when lock sync moves a third-party line", async () => {
    const root = await fixtureRepo("0.2.1");
    await expect(bumpRelease({
      repoRoot: root,
      version: "0.2.2",
      syncLocks: async () => {
        throw new Error("Cargo.lock moved more than Longhorn path versions:\n  serde 1.0.0 -> 1.0.1");
      },
      regenerateApiReference: async () => undefined,
    })).rejects.toThrow(/third-party|moved more than Longhorn path versions/);
  });
});

async function fixtureRepo(version: string): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "longhorn-release-bump-"));
  await mkdir(join(root, "packages/longhorn"), { recursive: true });
  await mkdir(join(root, "packages/longhorn-tauri"), { recursive: true });
  await mkdir(join(root, "packages/longhorn-poodle-svelte"), { recursive: true });
  await mkdir(join(root, "skills/agent-control"), { recursive: true });
  await mkdir(join(root, "docs/reference"), { recursive: true });
  await mkdir(join(root, "prototypes/example"), { recursive: true });
  await writeFile(join(root, "Cargo.toml"), `[workspace.package]\nversion = "${version}"\n\n[workspace.dependencies]\nlonghorn-core = { path = "crates/longhorn-core", version = "${version}" }\n`);
  await writeFile(join(root, "Cargo.lock"), `# lock\n\n[[package]]\nname = "longhorn-core"\nversion = "${version}"\n`);
  await writeFile(join(root, "prototypes/example/Cargo.lock"), `# lock\n\n[[package]]\nname = "longhorn-core"\nversion = "${version}"\n`);
  await writeFile(join(root, "packages/longhorn/package.json"), `{\n  "name": "@inflatable-cookie/longhorn",\n  "version": "${version}"\n}\n`);
  await writeFile(
    join(root, "packages/longhorn-tauri/package.json"),
    `{\n  "name": "@inflatable-cookie/longhorn-tauri",\n  "version": "${version}",\n  "peerDependencies": {\n    "@inflatable-cookie/longhorn": "${version}"\n  }\n}\n`,
  );
  await writeFile(
    join(root, "packages/longhorn-poodle-svelte/package.json"),
    `{\n  "name": "@inflatable-cookie/longhorn-poodle-svelte",\n  "version": "${version}",\n  "peerDependencies": {\n    "@inflatable-cookie/longhorn": "${version}",\n    "@inflatable-cookie/poodle-core": "0.4.2"\n  }\n}\n`,
  );
  await writeFile(join(root, "skills/agent-control/SKILL.md"), `---\nlonghorn_version: "${version}"\n---\n`);
  await writeFile(join(root, "CHANGELOG.md"), `# Changelog\n\n## [Unreleased]\n\n## [${version}] - 2026-09-25\n`);
  await writeFile(join(root, "docs/reference/api-surface.md"), `generated ${version}\n`);
  return root;
}
