export {
  EVENT_BUFFER_LIMIT,
  MAX_DEPTH,
  MAX_NODES,
  REF_ATTR,
  REF_PREFIX_GLOBAL,
  REF_SEQ_ATTR,
  SHIM_GLOBAL,
  TRUNCATED_REF,
  TRUNCATED_ROLE,
  installAgentControlShim,
  type AgentControlApi,
  type PageEvent,
  type PageState,
  type SemanticNode,
  type ShimResult,
  type ShimWorld,
  type ToolErrorBody,
  type WaitPredicate,
} from "./shim.ts";
