[package]
name = "longhorn-bindings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
longhorn-core = { workspace = true, features = ["bindings"] }
longhorn-bridge = { workspace = true, features = ["bindings"] }
longhorn-command = { workspace = true, features = ["bindings"] }
longhorn-command-config = { workspace = true, features = ["bindings"] }
longhorn-config = { workspace = true, features = ["bindings"] }
longhorn-history = { workspace = true, features = ["bindings"] }
longhorn-history-tree = { workspace = true, features = ["bindings"] }
longhorn-layout = { workspace = true, features = ["bindings"] }
longhorn-native-content = { workspace = true, features = ["bindings"] }
longhorn-notifications = { workspace = true, features = ["bindings"] }
longhorn-operation = { workspace = true, features = ["bindings"] }
longhorn-settings = { workspace = true, features = ["bindings"] }
longhorn-surfaces = { workspace = true, features = ["bindings"] }
longhorn-surface-transfer = { workspace = true, features = ["bindings"] }
longhorn-transfer = { workspace = true, features = ["bindings"] }
serde.workspace = true
serde_json.workspace = true
ts-rs.workspace = true

[lints]
workspace = true
