[package]
name = "longhorn-config-age"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
age.workspace = true
longhorn-config.workspace = true
serde.workspace = true

[dev-dependencies]
longhorn-core.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
